import type { Category, Word, CEFRLevel } from './types';

export const TYPE_COLORS: { [key: string]: string } = {
    'n': '#3b82f6',
    'v': '#16a34a',
    'adj': '#8b5cf6',
    'adv': '#f97316',
    'prep': '#dc2626',
    'conj': '#ca8a04',
    'n/v': '#475569',
    'pron': '#ec4899',
    'det': '#14b8a6',
    'phr v': '#0891b2',
    'idiom': '#d946ef',
};

export const INSPIRATIONAL_QUOTES = [
  { quote: "Học, học nữa, học mãi.", author: "V.I. Lenin" },
  { quote: "Học đi đôi với hành.", author: "Tục ngữ Việt Nam" },
  { quote: "Có công mài sắt, có ngày nên kim.", author: "Tục ngữ Việt Nam" },
  { quote: "Thất bại là mẹ thành công.", author: "Tục ngữ Việt Nam" },
  { quote: "Không có việc gì khó, chỉ sợ lòng không bền.", author: "Hồ Chí Minh" },
  { quote: "Đi một ngày đàng, học một sàng khôn.", author: "Tục ngữ Việt Nam" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs", translation: "Cách duy nhất để làm nên việc lớn là yêu những gì bạn làm." },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", translation: "Hãy tin rằng bạn có thể và bạn đã đi được nửa chặng đường." },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", translation: "Thành công không phải là cuối cùng, thất bại không phải là chết người: lòng can đảm để tiếp tục mới là điều đáng giá." },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", translation: "Tương lai thuộc về những người tin vào vẻ đẹp của giấc mơ của họ." },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", translation: "Việc bạn đi chậm thế nào không quan trọng, miễn là bạn không dừng lại." },
  { quote: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison", translation: "Thiên tài là một phần trăm cảm hứng và chín mươi chín phần trăm mồ hôi." },
  { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", translation: "Một người chưa bao giờ mắc lỗi là người chưa bao giờ thử bất cứ điều gì mới." },
  { quote: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu", translation: "Hành trình ngàn dặm bắt đầu từ một bước chân." },
  { quote: "Sự học là vô bờ.", author: "Tục ngữ Việt Nam" },
  { quote: "Kiến tha lâu cũng đầy tổ.", author: "Tục ngữ Việt Nam" },
  { quote: "Nước chảy đá mòn.", author: "Tục ngữ Việt Nam" },
  { quote: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison", translation: "Điểm yếu lớn nhất của chúng ta nằm ở việc bỏ cuộc. Cách chắc chắn nhất để thành công là luôn cố gắng thêm một lần nữa." },
  { quote: "The expert in anything was once a beginner.", author: "Helen Hayes", translation: "Chuyên gia trong bất kỳ lĩnh vực nào cũng từng là người mới bắt đầu." },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", translation: "Hãy sống như thể bạn sẽ chết vào ngày mai. Hãy học như thể bạn sẽ sống mãi mãi." },
  { quote: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb", translation: "Học vấn là một kho báu sẽ theo chủ nhân của nó đi khắp mọi nơi." },
  { quote: "Chớ thấy sóng cả mà ngã tay chèo.", author: "Tục ngữ Việt Nam" },
  { quote: "Có chí thì nên.", author: "Tục ngữ Việt Nam" },
  { quote: "Trên bước đường thành công không có dấu chân của kẻ lười biếng.", author: "Khuyết danh" },
  { quote: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King", translation: "Điều tuyệt vời của việc học là không ai có thể lấy nó đi khỏi bạn." },
  { quote: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", translation: "Một khoản đầu tư vào tri thức sẽ mang lại lợi nhuận cao nhất." },
  { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", translation: "Đừng nhìn đồng hồ; hãy làm những gì nó làm. Tiếp tục đi." },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain", translation: "Bí quyết để tiến về phía trước là bắt đầu." },
  { quote: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs", translation: "Thời gian của bạn là có hạn, đừng lãng phí nó để sống cuộc đời của người khác." },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", translation: "Luôn hướng về phía ánh nắng mặt trời—và bóng tối sẽ ngả lại sau lưng bạn." },
  { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", translation: "Những gì bạn đạt được khi hoàn thành mục tiêu không quan trọng bằng con người bạn trở thành khi hoàn thành mục tiêu đó." }
];

const rawCategories: (Omit<Category, 'words'> & { words: Omit<Word, 'color'>[] })[] = [
  // ==================== A1 LEVEL ====================
  {
    id: 'a1-greetings',
    name: 'Chào hỏi & Giới thiệu',
    level: 'A1',
    words: [
      { english: 'hello', type: 'n', pronunciation: '/həˈloʊ/', vietnamese: 'xin chào', example: 'Hello, my name is John. (Xin chào, tên tôi là John.)' },
      { english: 'goodbye', type: 'n', pronunciation: '/ˌɡʊdˈbaɪ/', vietnamese: 'tạm biệt', example: 'Goodbye! See you tomorrow. (Tạm biệt! Hẹn gặp bạn ngày mai.)' },
      { english: 'name', type: 'n', pronunciation: '/neɪm/', vietnamese: 'tên', example: 'What is your name? (Tên bạn là gì?)' },
      { english: 'thank you', type: 'n', pronunciation: '/θæŋk juː/', vietnamese: 'cảm ơn', example: 'Thank you for your help. (Cảm ơn sự giúp đỡ của bạn.)' },
      { english: 'please', type: 'adv', pronunciation: '/pliːz/', vietnamese: 'làm ơn', example: 'Could you help me, please? (Làm ơn, bạn có thể giúp tôi được không?)' },
      { english: 'sorry', type: 'adj', pronunciation: '/ˈsɑːri/', vietnamese: 'xin lỗi', example: 'I am sorry for being late. (Tôi xin lỗi vì đã đến muộn.)' },
      { english: 'morning', type: 'n', pronunciation: '/ˈmɔːrnɪŋ/', vietnamese: 'buổi sáng', example: 'Good morning! (Chào buổi sáng!)' },
      { english: 'afternoon', type: 'n', pronunciation: '/ˌæftərˈnuːn/', vietnamese: 'buổi chiều', example: 'Good afternoon, sir. (Chào buổi chiều, thưa ông.)' },
      { english: 'evening', type: 'n', pronunciation: '/ˈiːvnɪŋ/', vietnamese: 'buổi tối', example: 'Good evening, everyone. (Chào buổi tối mọi người.)' },
      { english: 'night', type: 'n', pronunciation: '/naɪt/', vietnamese: 'đêm', example: 'Good night! Sleep well. (Chúc ngủ ngon!)' },
      { english: 'yes', type: 'adv', pronunciation: '/jes/', vietnamese: 'vâng, có', example: 'Yes, I understand. (Vâng, tôi hiểu.)' },
      { english: 'no', type: 'adv', pronunciation: '/noʊ/', vietnamese: 'không', example: 'No, I don\'t want that. (Không, tôi không muốn điều đó.)' },
      { english: 'welcome', type: 'adj', pronunciation: '/ˈwelkəm/', vietnamese: 'chào mừng', example: 'You are welcome here. (Bạn được chào đón ở đây.)' },
      { english: 'excuse me', type: 'phr v', pronunciation: '/ɪkˈskjuːz miː/', vietnamese: 'xin lỗi', example: 'Excuse me, can I ask a question? (Xin lỗi, tôi có thể hỏi một câu được không?)' },
      { english: 'hi', type: 'n', pronunciation: '/haɪ/', vietnamese: 'chào', example: 'Hi! How are you? (Chào! Bạn khỏe không?)' },
      { english: 'bye', type: 'n', pronunciation: '/baɪ/', vietnamese: 'tạm biệt', example: 'Bye! Take care. (Tạm biệt! Bảo trọng nhé.)' },
    ],
  },
  {
    id: 'a1-family',
    name: 'Gia đình',
    level: 'A1',
    words: [
      { english: 'family', type: 'n', pronunciation: '/ˈfæməli/', vietnamese: 'gia đình', example: 'I have a small family. (Tôi có một gia đình nhỏ.)' },
      { english: 'mother', type: 'n', pronunciation: '/ˈmʌðər/', vietnamese: 'mẹ', example: 'My mother is a teacher. (Mẹ tôi là giáo viên.)' },
      { english: 'father', type: 'n', pronunciation: '/ˈfɑːðər/', vietnamese: 'bố', example: 'My father works in an office. (Bố tôi làm việc ở văn phòng.)' },
      { english: 'brother', type: 'n', pronunciation: '/ˈbrʌðər/', vietnamese: 'anh/em trai', example: 'He is my older brother. (Anh ấy là anh trai tôi.)' },
      { english: 'sister', type: 'n', pronunciation: '/ˈsɪstər/', vietnamese: 'chị/em gái', example: 'I have one sister. (Tôi có một người chị/em gái.)' },
      { english: 'son', type: 'n', pronunciation: '/sʌn/', vietnamese: 'con trai', example: 'They have one son. (Họ có một con trai.)' },
      { english: 'daughter', type: 'n', pronunciation: '/ˈdɔːtər/', vietnamese: 'con gái', example: 'His daughter is five years old. (Con gái anh ấy năm tuổi.)' },
      { english: 'parent', type: 'n', pronunciation: '/ˈperənt/', vietnamese: 'bố mẹ', example: 'My parents live in the countryside. (Bố mẹ tôi sống ở nông thôn.)' },
      { english: 'husband', type: 'n', pronunciation: '/ˈhʌzbənd/', vietnamese: 'chồng', example: 'Her husband is a doctor. (Chồng cô ấy là bác sĩ.)' },
      { english: 'wife', type: 'n', pronunciation: '/waɪf/', vietnamese: 'vợ', example: 'His wife is very kind. (Vợ anh ấy rất tốt bụng.)' },
      { english: 'grandmother', type: 'n', pronunciation: '/ˈɡrænmʌðər/', vietnamese: 'bà', example: 'My grandmother is 80 years old. (Bà tôi 80 tuổi.)' },
      { english: 'grandfather', type: 'n', pronunciation: '/ˈɡrænfɑːðər/', vietnamese: 'ông', example: 'My grandfather tells great stories. (Ông tôi kể chuyện rất hay.)' },
      { english: 'grandparents', type: 'n', pronunciation: '/ˈɡrænperənts/', vietnamese: 'ông bà', example: 'My grandparents visit us every Sunday. (Ông bà tôi đến thăm chúng tôi mỗi Chủ nhật.)'},
      { english: 'uncle', type: 'n', pronunciation: '/ˈʌŋkl/', vietnamese: 'chú, bác, cậu', example: 'My uncle lives in New York. (Chú tôi sống ở New York.)' },
      { english: 'aunt', type: 'n', pronunciation: '/ænt/', vietnamese: 'cô, dì, thím', example: 'My aunt is a nurse. (Cô tôi là y tá.)' },
      { english: 'cousin', type: 'n', pronunciation: '/ˈkʌzn/', vietnamese: 'anh/chị/em họ', example: 'I have three cousins. (Tôi có ba anh chị em họ.)' },
      { english: 'baby', type: 'n', pronunciation: '/ˈbeɪbi/', vietnamese: 'em bé', example: 'The baby is sleeping. (Em bé đang ngủ.)'},
      { english: 'child', type: 'n', pronunciation: '/tʃaɪld/', vietnamese: 'đứa trẻ', example: 'She is a very smart child. (Cô bé là một đứa trẻ rất thông minh.)'},
    ],
  },
  {
    id: 'a1-common-objects',
    name: 'Đồ vật thông dụng',
    level: 'A1',
    words: [
      { english: 'book', type: 'n', pronunciation: '/bʊk/', vietnamese: 'quyển sách', example: 'I am reading a book. (Tôi đang đọc một quyển sách.)' },
      { english: 'pen', type: 'n', pronunciation: '/pen/', vietnamese: 'cái bút', example: 'Can I borrow your pen? (Tôi có thể mượn bút của bạn không?)' },
      { english: 'pencil', type: 'n', pronunciation: '/ˈpensl/', vietnamese: 'bút chì', example: 'I need a pencil and paper to draw. (Tôi cần một cây bút chì và giấy để vẽ.)'},
      { english: 'table', type: 'n', pronunciation: '/ˈteɪbl/', vietnamese: 'cái bàn', example: 'The keys are on the table. (Chìa khóa ở trên bàn.)' },
      { english: 'chair', type: 'n', pronunciation: '/tʃer/', vietnamese: 'cái ghế', example: 'Please have a chair. (Xin mời ngồi.)' },
      { english: 'house', type: 'n', pronunciation: '/haʊs/', vietnamese: 'ngôi nhà', example: 'This is my house. (Đây là nhà của tôi.)' },
      { english: 'school', type: 'n', pronunciation: '/skuːl/', vietnamese: 'trường học', example: 'Children go to school to learn. (Trẻ em đến trường để học.)'},
      { english: 'car', type: 'n', pronunciation: '/kɑːr/', vietnamese: 'xe ô tô', example: 'She has a new car. (Cô ấy có một chiếc ô tô mới.)' },
      { english: 'phone', type: 'n', pronunciation: '/foʊn/', vietnamese: 'điện thoại', example: 'My phone is ringing. (Điện thoại của tôi đang reo.)' },
      { english: 'water', type: 'n', pronunciation: '/ˈwɔːtər/', vietnamese: 'nước', example: 'I need to drink some water. (Tôi cần uống một ít nước.)' },
      { english: 'door', type: 'n', pronunciation: '/dɔːr/', vietnamese: 'cửa', example: 'Close the door, please. (Làm ơn đóng cửa.)' },
      { english: 'window', type: 'n', pronunciation: '/ˈwɪndoʊ/', vietnamese: 'cửa sổ', example: 'Open the window. (Mở cửa sổ.)' },
      { english: 'clock', type: 'n', pronunciation: '/klɑːk/', vietnamese: 'đồng hồ', example: 'What time is it on the clock? (Mấy giờ rồi theo đồng hồ?)' },
      { english: 'computer', type: 'n', pronunciation: '/kəmˈpjuːtər/', vietnamese: 'máy tính', example: 'I use my computer every day. (Tôi dùng máy tính mỗi ngày.)' },
      { english: 'bag', type: 'n', pronunciation: '/bæɡ/', vietnamese: 'cái túi', example: 'Put it in the bag. (Bỏ nó vào túi.)' },
      { english: 'cup', type: 'n', pronunciation: '/kʌp/', vietnamese: 'cái cốc', example: 'I need a cup of tea. (Tôi cần một tách trà.)' },
      { english: 'glass', type: 'n', pronunciation: '/ɡlæs/', vietnamese: 'cái ly', example: 'Pour water into the glass. (Rót nước vào ly.)' },
      { english: 'key', type: 'n', pronunciation: '/kiː/', vietnamese: 'chìa khoá', example: 'Where are my keys? (Chìa khoá của tôi đâu rồi?)'},
      { english: 'money', type: 'n', pronunciation: '/ˈmʌni/', vietnamese: 'tiền', example: 'I need to save more money. (Tôi cần tiết kiệm thêm tiền.)'},
      { english: 'watch', type: 'n', pronunciation: '/wɑːtʃ/', vietnamese: 'đồng hồ đeo tay', example: 'He has an expensive watch. (Anh ấy có một chiếc đồng hồ đắt tiền.)'},
      { english: 'bed', type: 'n', pronunciation: '/bed/', vietnamese: 'cái giường', example: 'It\'s time to go to bed. (Đã đến giờ đi ngủ.)'},
      { english: 'spoon', type: 'n', pronunciation: '/spuːn/', vietnamese: 'cái thìa', example: 'I eat soup with a spoon. (Tôi ăn súp bằng thìa.)' },
      { english: 'fork', type: 'n', pronunciation: '/fɔːrk/', vietnamese: 'cái nĩa', example: 'You use a fork to eat salad. (Bạn dùng nĩa để ăn salad.)' },
      { english: 'knife', type: 'n', pronunciation: '/naɪf/', vietnamese: 'con dao', example: 'Be careful with that knife. (Hãy cẩn thận với con dao đó.)' },
      { english: 'plate', type: 'n', pronunciation: '/pleɪt/', vietnamese: 'cái đĩa', example: 'Put the food on the plate. (Đặt thức ăn lên đĩa.)' },
      { english: 'bottle', type: 'n', pronunciation: '/ˈbɑːtl/', vietnamese: 'cái chai', example: 'I have a bottle of water. (Tôi có một chai nước.)' },
    ],
  },
  {
    id: 'a1-food-drink',
    name: 'Đồ ăn & Thức uống (A1)',
    level: 'A1',
    words: [
        { english: 'apple', type: 'n', pronunciation: '/ˈæpl/', vietnamese: 'quả táo', example: 'An apple a day keeps the doctor away. (Mỗi ngày một quả táo giúp bạn tránh xa bác sĩ.)' },
        { english: 'banana', type: 'n', pronunciation: '/bəˈnænə/', vietnamese: 'quả chuối', example: 'Monkeys love to eat bananas. (Khỉ thích ăn chuối.)' },
        { english: 'orange', type: 'n', pronunciation: '/ˈɔːrɪndʒ/', vietnamese: 'quả cam', example: 'An orange is a sweet fruit. (Cam là một loại trái cây ngọt.)'},
        { english: 'bread', type: 'n', pronunciation: '/bred/', vietnamese: 'bánh mì', example: 'I eat bread for breakfast. (Tôi ăn bánh mì cho bữa sáng.)' },
        { english: 'cheese', type: 'n', pronunciation: '/tʃiːz/', vietnamese: 'phô mai', example: 'Mice like to eat cheese. (Chuột thích ăn phô mai.)' },
        { english: 'chicken', type: 'n', pronunciation: '/ˈtʃɪkɪn/', vietnamese: 'thịt gà', example: 'We are having chicken for dinner. (Chúng tôi sẽ ăn gà cho bữa tối.)' },
        { english: 'meat', type: 'n', pronunciation: '/miːt/', vietnamese: 'thịt', example: 'Lions eat meat. (Sư tử ăn thịt.)'},
        { english: 'egg', type: 'n', pronunciation: '/eɡ/', vietnamese: 'trứng', example: 'I like to eat a boiled egg. (Tôi thích ăn trứng luộc.)' },
        { english: 'fish', type: 'n', pronunciation: '/fɪʃ/', vietnamese: 'cá', example: 'Fish can swim in the water. (Cá có thể bơi trong nước.)' },
        { english: 'milk', type: 'n', pronunciation: '/mɪlk/', vietnamese: 'sữa', example: 'Drinking milk is good for your bones. (Uống sữa tốt cho xương của bạn.)' },
        { english: 'rice', type: 'n', pronunciation: '/raɪs/', vietnamese: 'cơm, gạo', example: 'Rice is a staple food in Vietnam. (Gạo là lương thực chính ở Việt Nam.)' },
        { english: 'coffee', type: 'n', pronunciation: '/ˈkɔːfi/', vietnamese: 'cà phê', example: 'My father drinks coffee every morning. (Bố tôi uống cà phê mỗi sáng.)' },
        { english: 'tea', type: 'n', pronunciation: '/tiː/', vietnamese: 'trà', example: 'Would you like a cup of tea? (Bạn có muốn một tách trà không?)' },
        { english: 'juice', type: 'n', pronunciation: '/dʒuːs/', vietnamese: 'nước ép', example: 'I like orange juice. (Tôi thích nước cam ép.)' },
        { english: 'sugar', type: 'n', pronunciation: '/ˈʃʊɡər/', vietnamese: 'đường', example: 'I put sugar in my coffee. (Tôi cho đường vào cà phê.)' },
        { english: 'salt', type: 'n', pronunciation: '/sɔːlt/', vietnamese: 'muối', example: 'The soup needs more salt. (Món súp cần thêm muối.)' },
        { english: 'butter', type: 'n', pronunciation: '/ˈbʌtər/', vietnamese: 'bơ', example: 'I like butter on my bread. (Tôi thích bơ trên bánh mì của mình.)' },
        { english: 'soup', type: 'n', pronunciation: '/suːp/', vietnamese: 'súp, canh', example: 'Chicken soup is good when you are sick. (Súp gà rất tốt khi bạn bị ốm.)' },
        { english: 'salad', type: 'n', pronunciation: '/ˈsæləd/', vietnamese: 'rau trộn', example: 'I had a salad for lunch. (Tôi đã ăn salad cho bữa trưa.)' },
    ]
  },
  {
    id: 'a1-basic-verbs',
    name: 'Động từ cơ bản',
    level: 'A1',
    words: [
        { english: 'be', type: 'v', pronunciation: '/biː/', vietnamese: 'thì, là, ở', example: 'I want to be a teacher. (Tôi muốn trở thành một giáo viên.)' },
        { english: 'have', type: 'v', pronunciation: '/hæv/', vietnamese: 'có', example: 'I have a dog. (Tôi có một con chó.)' },
        { english: 'do', type: 'v', pronunciation: '/duː/', vietnamese: 'làm', example: 'What do you do? (Bạn làm nghề gì?)' },
        { english: 'say', type: 'v', pronunciation: '/seɪ/', vietnamese: 'nói', example: 'He says he is tired. (Anh ấy nói anh ấy mệt.)' },
        { english: 'go', type: 'v', pronunciation: '/ɡoʊ/', vietnamese: 'đi', example: 'Let\'s go to the park. (Chúng ta hãy đi đến công viên.)' },
        { english: 'get', type: 'v', pronunciation: '/ɡet/', vietnamese: 'nhận, có được', example: 'I get many gifts on my birthday. (Tôi nhận được nhiều quà vào ngày sinh nhật.)' },
        { english: 'make', type: 'v', pronunciation: '/meɪk/', vietnamese: 'làm, tạo ra', example: 'She makes a beautiful cake. (Cô ấy làm một chiếc bánh đẹp.)' },
        { english: 'know', type: 'v', pronunciation: '/noʊ/', vietnamese: 'biết', example: 'I know his name. (Tôi biết tên anh ấy.)' },
        { english: 'think', type: 'v', pronunciation: '/θɪŋk/', vietnamese: 'nghĩ', example: 'I think it will rain. (Tôi nghĩ trời sẽ mưa.)' },
        { english: 'see', type: 'v', pronunciation: '/siː/', vietnamese: 'nhìn, thấy', example: 'I can see a bird. (Tôi có thể thấy một con chim.)' },
        { english: 'come', type: 'v', pronunciation: '/kʌm/', vietnamese: 'đến', example: 'Please come to my party. (Làm ơn hãy đến bữa tiệc của tôi.)' },
        { english: 'want', type: 'v', pronunciation: '/wɑːnt/', vietnamese: 'muốn', example: 'I want a new toy. (Tôi muốn một món đồ chơi mới.)' },
        { english: 'look', type: 'v', pronunciation: '/lʊk/', vietnamese: 'nhìn', example: 'Look at the beautiful flowers! (Hãy nhìn những bông hoa đẹp kìa!)' },
        { english: 'use', type: 'v', pronunciation: '/juːz/', vietnamese: 'sử dụng', example: 'Can I use your pen? (Tôi có thể dùng bút của bạn không?)' },
        { english: 'find', type: 'v', pronunciation: '/faɪnd/', vietnamese: 'tìm thấy', example: 'I can\'t find my keys. (Tôi không thể tìm thấy chìa khóa của mình.)' },
        { english: 'give', type: 'v', pronunciation: '/ɡɪv/', vietnamese: 'đưa, cho', example: 'Please give me the book. (Làm ơn đưa cho tôi quyển sách.)' },
        { english: 'tell', type: 'v', pronunciation: '/tel/', vietnamese: 'kể, bảo', example: 'Tell me a story. (Kể cho tôi một câu chuyện.)' },
        { english: 'work', type: 'v', pronunciation: '/wɜːrk/', vietnamese: 'làm việc', example: 'My parents work very hard. (Bố mẹ tôi làm việc rất chăm chỉ.)' },
        { english: 'eat', type: 'v', pronunciation: '/iːt/', vietnamese: 'ăn', example: 'What do you want to eat? (Bạn muốn ăn gì?)' },
        { english: 'drink', type: 'v', pronunciation: '/drɪŋk/', vietnamese: 'uống', example: 'You should drink more water. (Bạn nên uống nhiều nước hơn.)' },
    ]
  },
  {
    id: 'a1-weather',
    name: 'Thời tiết',
    level: 'A1',
    words: [
      { english: 'weather', type: 'n', pronunciation: '/ˈweðər/', vietnamese: 'thời tiết', example: 'What\'s the weather like today? (Thời tiết hôm nay thế nào?)' },
      { english: 'sunny', type: 'adj', pronunciation: '/ˈsʌni/', vietnamese: 'có nắng', example: 'It is a sunny day. (Hôm nay là một ngày nắng đẹp.)' },
      { english: 'rainy', type: 'adj', pronunciation: '/ˈreɪni/', vietnamese: 'có mưa', example: 'I don\'t like rainy days. (Tôi không thích những ngày mưa.)' },
      { english: 'cloudy', type: 'adj', pronunciation: '/ˈklaʊdi/', vietnamese: 'nhiều mây', example: 'The sky is cloudy. (Bầu trời nhiều mây.)' },
      { english: 'hot', type: 'adj', pronunciation: '/hɑːt/', vietnamese: 'nóng', example: 'It is very hot in the summer. (Mùa hè trời rất nóng.)' },
      { english: 'cold', type: 'adj', pronunciation: '/koʊld/', vietnamese: 'lạnh', example: 'Wear a coat, it\'s cold outside. (Mặc áo khoác vào, bên ngoài trời lạnh đấy.)' },
      { english: 'windy', type: 'adj', pronunciation: '/ˈwɪndi/', vietnamese: 'có gió', example: 'It is too windy to play outside. (Trời quá gió để chơi bên ngoài.)' },
      { english: 'snow', type: 'n', pronunciation: '/snoʊ/', vietnamese: 'tuyết', example: 'I love snow in winter. (Tôi thích tuyết vào mùa đông.)' },
      { english: 'rain', type: 'n', pronunciation: '/reɪn/', vietnamese: 'mưa', example: 'The rain is heavy today. (Hôm nay mưa to.)' },
      { english: 'sun', type: 'n', pronunciation: '/sʌn/', vietnamese: 'mặt trời', example: 'The sun is shining. (Mặt trời đang chiếu sáng.)' },
      { english: 'cool', type: 'adj', pronunciation: '/kuːl/', vietnamese: 'mát mẻ', example: 'The weather is cool in the autumn. (Thời tiết mát mẻ vào mùa thu.)'},
      { english: 'warm', type: 'adj', pronunciation: '/wɔːrm/', vietnamese: 'ấm áp', example: 'It\'s a warm spring day. (Đó là một ngày xuân ấm áp.)'},
    ],
  },
  {
    id: 'a1-animals',
    name: 'Động vật',
    level: 'A1',
    words: [
      { english: 'animal', type: 'n', pronunciation: '/ˈænɪml/', vietnamese: 'động vật', example: 'The lion is a wild animal. (Sư tử là một loài động vật hoang dã.)' },
      { english: 'dog', type: 'n', pronunciation: '/dɔːɡ/', vietnamese: 'con chó', example: 'My dog likes to play fetch. (Con chó của tôi thích chơi trò nhặt đồ.)' },
      { english: 'cat', type: 'n', pronunciation: '/kæt/', vietnamese: 'con mèo', example: 'The cat is sleeping on the sofa. (Con mèo đang ngủ trên ghế sofa.)' },
      { english: 'bird', type: 'n', pronunciation: '/bɜːrd/', vietnamese: 'con chim', example: 'A bird is singing in the tree. (Một con chim đang hót trên cây.)' },
      { english: 'fish', type: 'n', pronunciation: '/fɪʃ/', vietnamese: 'con cá', example: 'There are many fish in the river. (Có nhiều cá ở dưới sông.)' },
      { english: 'horse', type: 'n', pronunciation: '/hɔːrs/', vietnamese: 'con ngựa', example: 'She learned to ride a horse. (Cô ấy đã học cưỡi ngựa.)' },
      { english: 'cow', type: 'n', pronunciation: '/kaʊ/', vietnamese: 'con bò', example: 'A cow gives us milk. (Bò cho chúng ta sữa.)' },
      { english: 'pig', type: 'n', pronunciation: '/pɪɡ/', vietnamese: 'con lợn', example: 'Pigs like to play in the mud. (Lợn thích chơi trong bùn.)' },
      { english: 'monkey', type: 'n', pronunciation: '/ˈmʌŋki/', vietnamese: 'con khỉ', example: 'A monkey is climbing the tree. (Một con khỉ đang trèo cây.)' },
      { english: 'lion', type: 'n', pronunciation: '/ˈlaɪən/', vietnamese: 'sư tử', example: 'The lion is the king of the jungle. (Sư tử là vua của rừng xanh.)' },
      { english: 'tiger', type: 'n', pronunciation: '/ˈtaɪɡər/', vietnamese: 'con hổ', example: 'A tiger is a big cat. (Hổ là một loài mèo lớn.)' },
      { english: 'bear', type: 'n', pronunciation: '/ber/', vietnamese: 'con gấu', example: 'The bear is looking for honey. (Con gấu đang tìm mật ong.)' },
      { english: 'elephant', type: 'n', pronunciation: '/ˈelɪfənt/', vietnamese: 'con voi', example: 'An elephant has a long trunk. (Một con voi có một cái vòi dài.)' },
      { english: 'duck', type: 'n', pronunciation: '/dʌk/', vietnamese: 'con vịt', example: 'The duck is swimming in the pond. (Con vịt đang bơi trong ao.)' },
      { english: 'sheep', type: 'n', pronunciation: '/ʃiːp/', vietnamese: 'con cừu', example: 'Sheep give us wool. (Cừu cho chúng ta len.)' },
      { english: 'rabbit', type: 'n', pronunciation: '/ˈræbɪt/', vietnamese: 'con thỏ', example: 'A rabbit eats carrots. (Thỏ ăn cà rốt.)' },
    ]
  },
  {
    id: 'a1-colors-numbers',
    name: 'Màu sắc & Số đếm',
    level: 'A1',
    words: [
      { english: 'color', type: 'n', pronunciation: '/ˈkʌlər/', vietnamese: 'màu sắc', example: 'What is your favorite color? (Màu sắc yêu thích của bạn là gì?)' },
      { english: 'red', type: 'adj', pronunciation: '/red/', vietnamese: 'màu đỏ', example: 'The apple is red. (Quả táo màu đỏ.)' },
      { english: 'blue', type: 'adj', pronunciation: '/bluː/', vietnamese: 'màu xanh da trời', example: 'The sky is blue. (Bầu trời màu xanh.)' },
      { english: 'green', type: 'adj', pronunciation: '/ɡriːn/', vietnamese: 'màu xanh lá cây', example: 'The grass is green. (Cỏ màu xanh lá.)' },
      { english: 'yellow', type: 'adj', pronunciation: '/ˈjeloʊ/', vietnamese: 'màu vàng', example: 'The sun is yellow. (Mặt trời màu vàng.)' },
      { english: 'black', type: 'adj', pronunciation: '/blæk/', vietnamese: 'màu đen', example: 'He has a black cat. (Anh ấy có một con mèo đen.)' },
      { english: 'white', type: 'adj', pronunciation: '/waɪt/', vietnamese: 'màu trắng', example: 'She is wearing a white dress. (Cô ấy đang mặc một chiếc váy trắng.)' },
      { english: 'one', type: 'n', pronunciation: '/wʌn/', vietnamese: 'số một', example: 'I have one brother. (Tôi có một anh trai.)' },
      { english: 'two', type: 'n', pronunciation: '/tuː/', vietnamese: 'số hai', example: 'She has two dogs. (Cô ấy có hai con chó.)' },
      { english: 'three', type: 'n', pronunciation: '/θriː/', vietnamese: 'số ba', example: 'There are three books on the table. (Có ba quyển sách trên bàn.)' },
      { english: 'ten', type: 'n', pronunciation: '/ten/', vietnamese: 'số mười', example: 'I have ten fingers. (Tôi có mười ngón tay.)' },
      { english: 'hundred', type: 'n', pronunciation: '/ˈhʌndrəd/', vietnamese: 'trăm', example: 'One hundred cents make a dollar. (Một trăm xu bằng một đô la.)' },
    ]
  },

  // ==================== A2 LEVEL ====================
  {
    id: 'a2-daily-routines',
    name: 'Sinh hoạt hàng ngày',
    level: 'A2',
    words: [
      { english: 'get up', type: 'phr v', pronunciation: '/ɡet ʌp/', vietnamese: 'thức dậy', example: 'I get up at 7 AM every morning. (Tôi thức dậy lúc 7 giờ mỗi sáng.)' },
      { english: 'wake up', type: 'phr v', pronunciation: '/weɪk ʌp/', vietnamese: 'thức giấc', example: 'I wake up at 6 AM, but I get up at 6:30. (Tôi thức giấc lúc 6 giờ sáng, nhưng tôi ra khỏi giường lúc 6:30.)'},
      { english: 'have breakfast', type: 'phr v', pronunciation: '/hæv ˈbrekfəst/', vietnamese: 'ăn sáng', example: 'We have breakfast together. (Chúng tôi ăn sáng cùng nhau.)' },
      { english: 'go to work', type: 'phr v', pronunciation: '/ɡoʊ tə wɜːrk/', vietnamese: 'đi làm', example: 'He goes to work by bus. (Anh ấy đi làm bằng xe buýt.)' },
      { english: 'watch TV', type: 'phr v', pronunciation: '/wɑːtʃ ˌtiːˈviː/', vietnamese: 'xem TV', example: 'They watch TV in the evening. (Họ xem TV vào buổi tối.)' },
      { english: 'listen to music', type: 'phr v', pronunciation: '/ˈlɪsn tu ˈmjuːzɪk/', vietnamese: 'nghe nhạc', example: 'I like to listen to music when I study. (Tôi thích nghe nhạc khi học bài.)'},
      { english: 'usually', type: 'adv', pronunciation: '/ˈjuːʒuəli/', vietnamese: 'thường xuyên', example: 'I usually walk to school. (Tôi thường đi bộ đến trường.)' },
      { english: 'sometimes', type: 'adv', pronunciation: '/ˈsʌmtaɪmz/', vietnamese: 'thỉnh thoảng', example: 'Sometimes I play football. (Thỉnh thoảng tôi chơi bóng đá.)' },
      { english: 'always', type: 'adv', pronunciation: '/ˈɔːlweɪz/', vietnamese: 'luôn luôn', example: 'She always helps her mother. (Cô ấy luôn giúp đỡ mẹ.)' },
      { english: 'never', type: 'adv', pronunciation: '/ˈnevər/', vietnamese: 'không bao giờ', example: 'He never eats fast food. (Anh ấy không bao giờ ăn đồ ăn nhanh.)' },
      { english: 'take a shower', type: 'phr v', pronunciation: '/teɪk ə ˈʃaʊər/', vietnamese: 'tắm vòi sen', example: 'I take a shower every morning. (Tôi tắm mỗi sáng.)'},
      { english: 'cook dinner', type: 'phr v', pronunciation: '/kʊk ˈdɪnər/', vietnamese: 'nấu bữa tối', example: 'My mom cooks dinner for the family. (Mẹ tôi nấu bữa tối cho cả nhà.)'},
      { english: 'go to bed', type: 'phr v', pronunciation: '/ɡoʊ tə bed/', vietnamese: 'đi ngủ', example: 'I usually go to bed at 11 PM. (Tôi thường đi ngủ lúc 11 giờ tối.)'},
      { english: 'often', type: 'adv', pronunciation: '/ˈɔːfn/', vietnamese: 'thường', example: 'We often go to the cinema on weekends. (Chúng tôi thường đi xem phim vào cuối tuần.)'},
    ],
  },
  {
    id: 'a2-food-drink',
    name: 'Đồ ăn & Thức uống',
    level: 'A2',
    words: [
      { english: 'restaurant', type: 'n', pronunciation: '/ˈrestərɑːnt/', vietnamese: 'nhà hàng', example: 'Let\'s eat at that new restaurant. (Hãy ăn ở nhà hàng mới đó đi.)' },
      { english: 'delicious', type: 'adj', pronunciation: '/dɪˈlɪʃəs/', vietnamese: 'ngon', example: 'The food was delicious. (Đồ ăn rất ngon.)' },
      { english: 'hungry', type: 'adj', pronunciation: '/ˈhʌŋɡri/', vietnamese: 'đói', example: 'I am hungry. (Tôi đói.)' },
      { english: 'thirsty', type: 'adj', pronunciation: '/ˈθɜːrsti/', vietnamese: 'khát', example: 'I am thirsty. (Tôi khát.)' },
      { english: 'menu', type: 'n', pronunciation: '/ˈmenjuː/', vietnamese: 'thực đơn', example: 'Could we see the menu? (Cho chúng tôi xem thực đơn?)' },
      { english: 'order', type: 'v', pronunciation: '/ˈɔːrdər/', vietnamese: 'gọi món', example: 'Are you ready to order? (Bạn đã sẵn sàng gọi món chưa?)' },
      { english: 'waiter', type: 'n', pronunciation: '/ˈweɪtər/', vietnamese: 'bồi bàn nam', example: 'The waiter brought us the bill. (Người bồi bàn đã mang hóa đơn.)' },
      { english: 'bill', type: 'n', pronunciation: '/bɪl/', vietnamese: 'hóa đơn', example: 'Can we have the bill, please? (Làm ơn cho chúng tôi xin hóa đơn?)' },
      { english: 'vegetable', type: 'n', pronunciation: '/ˈvedʒtəbl/', vietnamese: 'rau củ', example: 'You should eat more vegetables. (Bạn nên ăn nhiều rau củ hơn.)' },
      { english: 'fruit', type: 'n', pronunciation: '/fruːt/', vietnamese: 'trái cây', example: 'Fruit is healthy and delicious. (Trái cây vừa tốt cho sức khỏe vừa ngon.)' },
      { english: 'dessert', type: 'n', pronunciation: '/dɪˈzɜːrt/', vietnamese: 'tráng miệng', example: 'What do you want for dessert? (Bạn muốn dùng gì cho món tráng miệng?)' },
    ],
  },
  {
    id: 'a2-shopping',
    name: 'Mua sắm',
    level: 'A2',
    words: [
      { english: 'price', type: 'n', pronunciation: '/praɪs/', vietnamese: 'giá cả', example: 'What is the price? (Giá là bao nhiêu?)' },
      { english: 'expensive', type: 'adj', pronunciation: '/ɪkˈspensɪv/', vietnamese: 'đắt', example: 'This watch is too expensive. (Cái đồng hồ này quá đắt.)' },
      { english: 'cheap', type: 'adj', pronunciation: '/tʃiːp/', vietnamese: 'rẻ', example: 'I bought a cheap phone. (Tôi đã mua một chiếc điện thoại rẻ.)' },
      { english: 'money', type: 'n', pronunciation: '/ˈmʌni/', vietnamese: 'tiền', example: 'I need to save more money. (Tôi cần tiết kiệm thêm tiền.)' },
      { english: 'buy', type: 'v', pronunciation: '/baɪ/', vietnamese: 'mua', example: 'I want to buy a new dress. (Tôi muốn mua một chiếc váy mới.)' },
      { english: 'sell', type: 'v', pronunciation: '/sel/', vietnamese: 'bán', example: 'They sell fresh fruit. (Họ bán trái cây tươi.)' },
      { english: 'store', type: 'n', pronunciation: '/stɔːr/', vietnamese: 'cửa hàng', example: 'Let\'s go to the clothing store. (Chúng ta hãy đến cửa hàng quần áo.)' },
      { english: 'market', type: 'n', pronunciation: '/ˈmɑːrkɪt/', vietnamese: 'chợ', example: 'My mother goes to the market every morning. (Mẹ tôi đi chợ mỗi sáng.)' },
      { english: 'pay', type: 'v', pronunciation: '/peɪ/', vietnamese: 'trả tiền', example: 'How would you like to pay? (Bạn muốn thanh toán bằng cách nào?)' },
      { english: 'cash', type: 'n', pronunciation: '/kæʃ/', vietnamese: 'tiền mặt', example: 'I will pay in cash. (Tôi sẽ trả bằng tiền mặt.)' },
      { english: 'credit card', type: 'n', pronunciation: '/ˈkredɪt kɑːrd/', vietnamese: 'thẻ tín dụng', example: 'You can pay with cash or credit card. (Bạn có thể trả bằng tiền mặt hoặc thẻ tín dụng.)'},
      { english: 'receipt', type: 'n', pronunciation: '/rɪˈsiːt/', vietnamese: 'biên lai', example: 'Please keep the receipt for your purchase. (Vui lòng giữ lại biên lai cho món hàng của bạn.)'},
    ],
  },
  {
    id: 'a2-travel',
    name: 'Du lịch',
    level: 'A2',
    words: [
      { english: 'airport', type: 'n', pronunciation: '/ˈerpɔːrt/', vietnamese: 'sân bay', example: 'We need to be at the airport early. (Chúng ta cần có mặt tại sân bay sớm.)' },
      { english: 'ticket', type: 'n', pronunciation: '/ˈtɪkɪt/', vietnamese: 'vé', example: 'Have you bought your ticket yet? (Bạn đã mua vé chưa?)' },
      { english: 'hotel', type: 'n', pronunciation: '/hoʊˈtel/', vietnamese: 'khách sạn', example: 'We are staying at a hotel. (Chúng tôi đang ở khách sạn.)' },
      { english: 'passport', type: 'n', pronunciation: '/ˈpæspɔːrt/', vietnamese: 'hộ chiếu', example: 'Don\'t forget your passport. (Đừng quên hộ chiếu.)' },
      { english: 'journey', type: 'n', pronunciation: '/ˈdʒɜːrni/', vietnamese: 'chuyến đi', example: 'It was a long journey. (Đó là một chuyến đi dài.)' },
      { english: 'visit', type: 'v', pronunciation: '/ˈvɪzɪt/', vietnamese: 'thăm', example: 'We are going to visit our grandparents. (Chúng tôi sẽ đi thăm ông bà.)' },
      { english: 'tourist', type: 'n', pronunciation: '/ˈtʊrɪst/', vietnamese: 'khách du lịch', example: 'Many tourists visit this city. (Nhiều khách du lịch đến thăm thành phố này.)' },
      { english: 'holiday', type: 'n', pronunciation: '/ˈhɑːlədeɪ/', vietnamese: 'kỳ nghỉ', example: 'Where are you going for your summer holiday? (Bạn sẽ đi đâu vào kỳ nghỉ hè?)' },
      { english: 'vacation', type: 'n', pronunciation: '/veɪˈkeɪʃn/', vietnamese: 'kỳ nghỉ', example: 'We are going on vacation to the beach. (Chúng tôi sẽ đi nghỉ ở bãi biển.)'},
      { english: 'map', type: 'n', pronunciation: '/mæp/', vietnamese: 'bản đồ', example: 'We need a map to find the way. (Chúng ta cần một tấm bản đồ để tìm đường.)' },
      { english: 'train', type: 'n', pronunciation: '/treɪn/', vietnamese: 'tàu hỏa', example: 'We will travel by train. (Chúng ta sẽ đi du lịch bằng tàu hỏa.)' },
      { english: 'bus', type: 'n', pronunciation: '/bʌs/', vietnamese: 'xe buýt', example: 'The bus is crowded in the morning. (Xe buýt đông đúc vào buổi sáng.)' },
      { english: 'plane', type: 'n', pronunciation: '/pleɪn/', vietnamese: 'máy bay', example: 'I have never traveled by plane. (Tôi chưa bao giờ đi du lịch bằng máy bay.)' },
      { english: 'station', type: 'n', pronunciation: '/ˈsteɪʃn/', vietnamese: 'nhà ga', example: 'Let\'s meet at the train station. (Hãy gặp nhau ở ga tàu.)' },
      { english: 'luggage', type: 'n', pronunciation: '/ˈlʌɡɪdʒ/', vietnamese: 'hành lý', example: 'How many pieces of luggage do you have? (Bạn có bao nhiêu kiện hành lý?)' },
      { english: 'camera', type: 'n', pronunciation: '/ˈkæmərə/', vietnamese: 'máy ảnh', example: 'I bought a new camera to take pictures. (Tôi đã mua một chiếc máy ảnh mới để chụp hình.)'},
      { english: 'beach', type: 'n', pronunciation: '/biːtʃ/', vietnamese: 'bãi biển', example: 'The children are playing on the beach. (Bọn trẻ đang chơi trên bãi biển.)' },
      { english: 'mountain', type: 'n', pronunciation: '/ˈmaʊntn/', vietnamese: 'núi', example: 'We went hiking in the mountains. (Chúng tôi đã đi leo núi.)' },
    ],
  },
  {
    id: 'a2-health',
    name: 'Sức khỏe',
    level: 'A2',
    words: [
      { english: 'doctor', type: 'n', pronunciation: '/ˈdɑːktər/', vietnamese: 'bác sĩ', example: 'I need to see a doctor. (Tôi cần đi gặp bác sĩ.)' },
      { english: 'hospital', type: 'n', pronunciation: '/ˈhɑːspɪtl/', vietnamese: 'bệnh viện', example: 'She was taken to the hospital. (Cô ấy đã được đưa đến bệnh viện.)' },
      { english: 'headache', type: 'n', pronunciation: '/ˈhedeɪk/', vietnamese: 'đau đầu', example: 'I have a terrible headache. (Tôi bị đau đầu kinh khủng.)' },
      { english: 'healthy', type: 'adj', pronunciation: '/ˈhelθi/', vietnamese: 'khỏe mạnh', example: 'Eating vegetables is healthy. (Ăn rau rất tốt cho sức khỏe.)' },
      { english: 'exercise', type: 'v', pronunciation: '/ˈeksərsaɪz/', vietnamese: 'tập thể dục', example: 'You should exercise regularly. (Bạn nên tập thể dục thường xuyên.)' },
      { english: 'sick', type: 'adj', pronunciation: '/sɪk/', vietnamese: 'ốm', example: 'He is sick, so he can\'t go to school. (Cậu ấy bị ốm nên không thể đến trường.)' },
      { english: 'medicine', type: 'n', pronunciation: '/ˈmedɪsn/', vietnamese: 'thuốc', example: 'The doctor gave me some medicine. (Bác sĩ đã cho tôi một ít thuốc.)' },
    ],
  },
   {
    id: 'a2-jobs',
    name: 'Nghề nghiệp',
    level: 'A2',
    words: [
      { english: 'teacher', type: 'n', pronunciation: '/ˈtiːtʃər/', vietnamese: 'giáo viên', example: 'My mother is a teacher. (Mẹ tôi là giáo viên.)' },
      { english: 'student', type: 'n', pronunciation: '/ˈstuːdnt/', vietnamese: 'học sinh, sinh viên', example: 'I am a student at a big university. (Tôi là sinh viên tại một trường đại học lớn.)' },
      { english: 'doctor', type: 'n', pronunciation: '/ˈdɑːktər/', vietnamese: 'bác sĩ', example: 'You should see a doctor if you are sick. (Bạn nên đi gặp bác sĩ nếu bạn bị ốm.)' },
      { english: 'nurse', type: 'n', pronunciation: '/nɜːrs/', vietnamese: 'y tá', example: 'The nurse is very kind. (Cô y tá rất tốt bụng.)' },
      { english: 'engineer', type: 'n', pronunciation: '/ˌendʒɪˈnɪr/', vietnamese: 'kỹ sư', example: 'My brother is an engineer. (Anh trai tôi là một kỹ sư.)' },
      { english: 'artist', type: 'n', pronunciation: '/ˈɑːrtɪst/', vietnamese: 'họa sĩ', example: 'She is a talented artist. (Cô ấy là một họa sĩ tài năng.)' },
      { english: 'singer', type: 'n', pronunciation: '/ˈsɪŋər/', vietnamese: 'ca sĩ', example: 'He wants to be a famous singer. (Anh ấy muốn trở thành một ca sĩ nổi tiếng.)' },
      { english: 'cook', type: 'n', pronunciation: '/kʊk/', vietnamese: 'đầu bếp', example: 'The cook made a delicious meal. (Đầu bếp đã làm một bữa ăn ngon.)' },
    ],
  },
  {
    id: 'a2-clothes',
    name: 'Quần áo',
    level: 'A2',
    words: [
      { english: 'clothes', type: 'n', pronunciation: '/kloʊðz/', vietnamese: 'quần áo', example: 'I need to buy some new clothes. (Tôi cần mua một ít quần áo mới.)' },
      { english: 'shirt', type: 'n', pronunciation: '/ʃɜːrt/', vietnamese: 'áo sơ mi', example: 'He is wearing a blue shirt. (Anh ấy đang mặc một chiếc áo sơ mi màu xanh.)' },
      { english: 't-shirt', type: 'n', pronunciation: '/ˈtiː ʃɜːrt/', vietnamese: 'áo phông', example: 'I like wearing a t-shirt in the summer. (Tôi thích mặc áo phông vào mùa hè.)' },
      { english: 'pants', type: 'n', pronunciation: '/pænts/', vietnamese: 'quần dài', example: 'These pants are too long for me. (Cái quần này quá dài đối với tôi.)' },
      { english: 'jeans', type: 'n', pronunciation: '/dʒiːnz/', vietnamese: 'quần bò', example: 'She bought a new pair of jeans. (Cô ấy đã mua một chiếc quần bò mới.)' },
      { english: 'dress', type: 'n', pronunciation: '/dres/', vietnamese: 'váy liền', example: 'She wore a beautiful dress to the party. (Cô ấy đã mặc một chiếc váy đẹp đến bữa tiệc.)' },
      { english: 'skirt', type: 'n', pronunciation: '/skɜːrt/', vietnamese: 'chân váy', example: 'She is wearing a long skirt. (Cô ấy đang mặc một chiếc chân váy dài.)' },
      { english: 'jacket', type: 'n', pronunciation: '/ˈdʒækɪt/', vietnamese: 'áo khoác', example: 'It\'s cold outside, wear a jacket. (Ngoài trời lạnh, hãy mặc áo khoác vào.)' },
      { english: 'shoes', type: 'n', pronunciation: '/ʃuːz/', vietnamese: 'giày', example: 'I need to buy new shoes for running. (Tôi cần mua giày mới để chạy bộ.)' },
      { english: 'hat', type: 'n', pronunciation: '/hæt/', vietnamese: 'mũ', example: 'He wears a hat to protect himself from the sun. (Anh ấy đội mũ để bảo vệ khỏi ánh nắng mặt trời.)' },
      { english: 'socks', type: 'n', pronunciation: '/sɑːks/', vietnamese: 'tất, vớ', example: 'I need a new pair of socks. (Tôi cần một đôi tất mới.)' },
      { english: 'coat', type: 'n', pronunciation: '/koʊt/', vietnamese: 'áo choàng', example: 'It is cold, you should wear a coat. (Trời lạnh, bạn nên mặc áo choàng.)' },
      { english: 'sweater', type: 'n', pronunciation: '/ˈswetər/', vietnamese: 'áo len', example: 'My grandmother knitted this sweater for me. (Bà tôi đã đan chiếc áo len này cho tôi.)' },
      { english: 'glasses', type: 'n', pronunciation: '/ˈɡlæsɪz/', vietnamese: 'kính mắt', example: 'I can\'t read without my glasses. (Tôi không thể đọc nếu không có kính.)' },
    ]
  },
  {
    id: 'a2-places',
    name: 'Địa điểm',
    level: 'A2',
    words: [
      { english: 'place', type: 'n', pronunciation: '/pleɪs/', vietnamese: 'địa điểm, nơi', example: 'This is a nice place for a picnic. (Đây là một nơi tốt để đi dã ngoại.)' },
      { english: 'city', type: 'n', pronunciation: '/ˈsɪti/', vietnamese: 'thành phố', example: 'Hanoi is a big city. (Hà Nội là một thành phố lớn.)' },
      { english: 'school', type: 'n', pronunciation: '/skuːl/', vietnamese: 'trường học', example: 'The children go to school every day. (Trẻ em đến trường mỗi ngày.)' },
      { english: 'park', type: 'n', pronunciation: '/pɑːrk/', vietnamese: 'công viên', example: 'Let\'s go for a walk in the park. (Hãy đi dạo trong công viên.)' },
      { english: 'supermarket', type: 'n', pronunciation: '/ˈsuːpərmɑːrkɪt/', vietnamese: 'siêu thị', example: 'I need to go to the supermarket to buy food. (Tôi cần đi siêu thị để mua đồ ăn.)' },
      { english: 'bank', type: 'n', pronunciation: '/bæŋk/', vietnamese: 'ngân hàng', example: 'I need to withdraw some money from the bank. (Tôi cần rút một ít tiền từ ngân hàng.)' },
      { english: 'post office', type: 'n', pronunciation: '/ˈpoʊst ɒfɪs/', vietnamese: 'bưu điện', example: 'You can buy stamps at the post office. (Bạn có thể mua tem ở bưu điện.)' },
      { english: 'library', type: 'n', pronunciation: '/ˈlaɪbreri/', vietnamese: 'thư viện', example: 'I like to borrow books from the library. (Tôi thích mượn sách từ thư viện.)' },
      { english: 'cinema', type: 'n', pronunciation: '/ˈsɪnəmə/', vietnamese: 'rạp chiếu phim', example: 'We are going to the cinema to watch a new movie. (Chúng tôi sẽ đến rạp chiếu phim để xem một bộ phim mới.)' },
      { english: 'restaurant', type: 'n', pronunciation: '/ˈrestərɑːnt/', vietnamese: 'nhà hàng', example: 'We ate at an Italian restaurant. (Chúng tôi đã ăn ở một nhà hàng Ý.)' },
      { english: 'cafe', type: 'n', pronunciation: '/kæˈfeɪ/', vietnamese: 'quán cà phê', example: 'Let\'s meet at the cafe on the corner. (Hãy gặp nhau ở quán cà phê ở góc phố.)' },
      { english: 'museum', type: 'n', pronunciation: '/mjuˈziːəm/', vietnamese: 'bảo tàng', example: 'The city has a famous art museum. (Thành phố có một bảo tàng nghệ thuật nổi tiếng.)' },
    ]
  },


  // ==================== B1 LEVEL ====================
  {
    id: 'b1-work',
    name: 'Công việc',
    level: 'B1',
    words: [
      { english: 'appointment', type: 'n', pronunciation: '/əˈpɔɪntmənt/', vietnamese: 'cuộc hẹn', example: 'I have a doctor\'s appointment at 3 PM. (Tôi có cuộc hẹn với bác sĩ lúc 3 giờ chiều.)' },
      { english: 'employee', type: 'n', pronunciation: '/ɪmˈplɔɪiː/', vietnamese: 'nhân viên', example: 'The company has over 100 employees. (Công ty có hơn 100 nhân viên.)' },
      { english: 'office', type: 'n', pronunciation: '/ˈɔːfɪs/', vietnamese: 'văn phòng', example: 'My father works in an office in the city center. (Bố tôi làm việc tại một văn phòng ở trung tâm thành phố.)'},
      { english: 'meeting', type: 'n', pronunciation: '/ˈmiːtɪŋ/', vietnamese: 'cuộc họp', example: 'The meeting was postponed. (Cuộc họp đã bị hoãn lại.)' },
      { english: 'project', type: 'n', pronunciation: '/ˈprɑːdʒekt/', vietnamese: 'dự án', example: 'We are working on a new project. (Chúng tôi đang thực hiện một dự án mới.)' },
      { english: 'report', type: 'n', pronunciation: '/rɪˈpɔːrt/', vietnamese: 'báo cáo', example: 'I have to finish this report by Friday. (Tôi phải hoàn thành báo cáo này trước thứ Sáu.)'},
      { english: 'salary', type: 'n', pronunciation: '/ˈsæləri/', vietnamese: 'lương', example: 'He receives a good salary. (Anh ấy nhận được một mức lương tốt.)' },
      { english: 'manager', type: 'n', pronunciation: '/ˈmænɪdʒər/', vietnamese: 'quản lý', example: 'She is the manager. (Cô ấy là quản lý.)' },
      { english: 'deadline', type: 'n', pronunciation: '/ˈdedlaɪn/', vietnamese: 'hạn chót', example: 'The deadline is Friday. (Hạn chót là thứ Sáu.)' },
      { english: 'experience', type: 'n', pronunciation: '/ɪkˈspɪriəns/', vietnamese: 'kinh nghiệm', example: 'Do you have any experience? (Bạn có kinh nghiệm nào không?)' },
      { english: 'colleague', type: 'n', pronunciation: '/ˈkɑːliːɡ/', vietnamese: 'đồng nghiệp', example: 'I went to lunch with my colleagues. (Tôi đã đi ăn trưa với các đồng nghiệp.)' },
      { english: 'career', type: 'n', pronunciation: '/kəˈrɪr/', vietnamese: 'sự nghiệp', example: 'She is focused on her career. (Cô ấy tập trung vào sự nghiệp của mình.)'},
      { english: 'company', type: 'n', pronunciation: '/ˈkʌmpəni/', vietnamese: 'công ty', example: 'He works for a large technology company. (Anh ấy làm việc cho một công ty công nghệ lớn.)'},
      { english: 'task', type: 'n', pronunciation: '/tæsk/', vietnamese: 'nhiệm vụ', example: 'My first task of the day is to check emails. (Nhiệm vụ đầu tiên trong ngày của tôi là kiểm tra email.)'},
      { english: 'interview', type: 'n', pronunciation: '/ˈɪntərvjuː/', vietnamese: 'phỏng vấn', example: 'I have a job interview tomorrow. (Tôi có một cuộc phỏng vấn xin việc vào ngày mai.)' },
      { english: 'resume', type: 'n', pronunciation: '/ˈrezəmeɪ/', vietnamese: 'sơ yếu lý lịch', example: 'You should update your resume. (Bạn nên cập nhật sơ yếu lý lịch của mình.)' },
      { english: 'promotion', type: 'n', pronunciation: '/prəˈmoʊʃn/', vietnamese: 'sự thăng chức', example: 'He received a promotion to senior manager. (Anh ấy đã được thăng chức lên quản lý cấp cao.)' },
      { english: 'department', type: 'n', pronunciation: '/dɪˈpɑːrtmənt/', vietnamese: 'phòng ban', example: 'She works in the marketing department. (Cô ấy làm việc ở phòng marketing.)' },
    ],
  },
  {
    id: 'b1-education',
    name: 'Giáo dục',
    level: 'B1',
    words: [
      { english: 'university', type: 'n', pronunciation: '/ˌjuːnɪˈvɜːrsəti/', vietnamese: 'trường đại học', example: 'She is studying at a famous university. (Cô ấy đang học tại một trường đại học nổi tiếng.)' },
      { english: 'course', type: 'n', pronunciation: '/kɔːrs/', vietnamese: 'khóa học', example: 'I signed up for an online English course. (Tôi đã đăng ký một khóa học tiếng Anh trực tuyến.)'},
      { english: 'exam', type: 'n', pronunciation: '/ɪɡˈzæm/', vietnamese: 'kỳ thi', example: 'I have to study for my final exams. (Tôi phải học cho kỳ thi cuối kỳ.)' },
      { english: 'degree', type: 'n', pronunciation: '/dɪˈɡriː/', vietnamese: 'bằng cấp', example: 'He has a degree in computer science. (Anh ấy có bằng cử nhân ngành khoa học máy tính.)' },
      { english: 'subject', type: 'n', pronunciation: '/ˈsʌbdʒɪkt/', vietnamese: 'môn học', example: 'My favorite subject is history. (Môn học yêu thích của tôi là lịch sử.)' },
      { english: 'knowledge', type: 'n', pronunciation: '/ˈnɑːlɪdʒ/', vietnamese: 'kiến thức', example: 'Reading books is a good way to gain knowledge. (Đọc sách là cách tốt để thu nhận kiến thức.)' },
      { english: 'grade', type: 'n', pronunciation: '/ɡreɪd/', vietnamese: 'điểm số, lớp', example: 'She got a good grade on the test. (Cô ấy đã đạt điểm cao trong bài kiểm tra.)' },
      { english: 'homework', type: 'n', pronunciation: '/ˈhoʊmwɜːrk/', vietnamese: 'bài tập về nhà', example: 'The teacher gave us a lot of homework. (Giáo viên đã cho chúng tôi rất nhiều bài tập về nhà.)'},
      { english: 'professor', type: 'n', pronunciation: '/prəˈfesər/', vietnamese: 'giáo sư', example: 'The professor explained the theory very well. (Vị giáo sư đã giải thích lý thuyết rất tốt.)' },
      { english: 'research', type: 'n', pronunciation: '/ˈriːsɜːrtʃ/', vietnamese: 'nghiên cứu', example: 'He is doing research on climate change. (Anh ấy đang nghiên cứu về biến đổi khí hậu.)' },
    ],
  },
  {
    id: 'b1-opinions',
    name: 'Quan điểm & Cảm xúc',
    level: 'B1',
    words: [
      { english: 'believe', type: 'v', pronunciation: '/bɪˈliːv/', vietnamese: 'tin tưởng', example: 'I believe we can solve this problem. (Tôi tin rằng chúng ta có thể giải quyết vấn đề này.)' },
      { english: 'disagree', type: 'v', pronunciation: '/ˌdɪsəˈɡriː/', vietnamese: 'không đồng ý', example: 'I disagree with your opinion. (Tôi không đồng ý với ý kiến của bạn.)' },
      { english: 'excited', type: 'adj', pronunciation: '/ɪkˈsaɪtɪd/', vietnamese: 'hào hứng', example: 'She was excited about her trip. (Cô ấy rất hào hứng về chuyến đi.)' },
      { english: 'worried', type: 'adj', pronunciation: '/ˈwɜːrid/', vietnamese: 'lo lắng', example: 'I am worried about the exam results. (Tôi lo lắng về kết quả kỳ thi.)' },
      { english: 'opinion', type: 'n', pronunciation: '/əˈpɪnjən/', vietnamese: 'ý kiến', example: 'In my opinion, this is the best solution. (Theo ý kiến của tôi, đây là giải pháp tốt nhất.)' },
      { english: 'suggest', type: 'v', pronunciation: '/səɡˈdʒest/', vietnamese: 'gợi ý', example: 'I suggest that we take a break. (Tôi gợi ý chúng ta nên nghỉ giải lao.)' },
      { english: 'probably', type: 'adv', pronunciation: '/ˈprɑːbəbli/', vietnamese: 'có lẽ', example: 'It will probably rain tomorrow. (Ngày mai có lẽ trời sẽ mưa.)' },
      { english: 'disappointed', type: 'adj', pronunciation: '/ˌdɪsəˈpɔɪntɪd/', vietnamese: 'thất vọng', example: 'He was disappointed with his test score. (Anh ấy thất vọng với điểm kiểm tra.)' },
      { english: 'prefer', type: 'v', pronunciation: '/prɪˈfɜːr/', vietnamese: 'thích hơn', example: 'I prefer tea to coffee. (Tôi thích trà hơn cà phê.)' },
      { english: 'agree', type: 'v', pronunciation: '/əˈɡriː/', vietnamese: 'đồng ý', example: 'I agree with you completely. (Tôi hoàn toàn đồng ý với bạn.)' },
      { english: 'surprised', type: 'adj', pronunciation: '/sərˈpraɪzd/', vietnamese: 'ngạc nhiên', example: 'I was surprised to see him there. (Tôi đã ngạc nhiên khi thấy anh ấy ở đó.)' },
    ],
  },
  {
    id: 'b1-environment',
    name: 'Môi trường',
    level: 'B1',
    words: [
      { english: 'pollution', type: 'n', pronunciation: '/pəˈluːʃn/', vietnamese: 'sự ô nhiễm', example: 'Air pollution is a serious problem. (Ô nhiễm không khí là một vấn đề nghiêm trọng.)' },
      { english: 'recycle', type: 'v', pronunciation: '/ˌriːˈsaɪkl/', vietnamese: 'tái chế', example: 'We should recycle paper and plastic. (Chúng ta nên tái chế giấy và nhựa.)' },
      { english: 'protect', type: 'v', pronunciation: '/prəˈtekt/', vietnamese: 'bảo vệ', example: 'We need to protect endangered animals. (Chúng ta cần bảo vệ các loài động vật có nguy cơ tuyệt chủng.)' },
      { english: 'climate change', type: 'n', pronunciation: '/ˈklaɪmət tʃeɪndʒ/', vietnamese: 'biến đổi khí hậu', example: 'Climate change is causing global temperatures to rise. (Biến đổi khí hậu đang làm cho nhiệt độ toàn cầu tăng lên.)' },
      { english: 'environment', type: 'n', pronunciation: '/ɪnˈvaɪrənmənt/', vietnamese: 'môi trường', example: 'It is important to keep our environment clean. (Việc giữ cho môi trường sạch sẽ là rất quan trọng.)' },
      { english: 'energy', type: 'n', pronunciation: '/ˈenərdʒi/', vietnamese: 'năng lượng', example: 'We should save energy to protect the environment. (Chúng ta nên tiết kiệm năng lượng để bảo vệ môi trường.)' },
      { english: 'waste', type: 'n', pronunciation: '/weɪst/', vietnamese: 'rác thải', example: 'We need to reduce plastic waste. (Chúng ta cần giảm thiểu rác thải nhựa.)' },
    ],
  },
  {
    id: 'b1-hobbies',
    name: 'Sở thích',
    level: 'B1',
    words: [
      { english: 'hobby', type: 'n', pronunciation: '/ˈhɑːbi/', vietnamese: 'sở thích', example: 'My hobby is playing the guitar. (Sở thích của tôi là chơi guitar.)' },
      { english: 'photography', type: 'n', pronunciation: '/fəˈtɑːɡrəfi/', vietnamese: 'nhiếp ảnh', example: 'She is interested in photography. (Cô ấy quan tâm đến nhiếp ảnh.)' },
      { english: 'gardening', type: 'n', pronunciation: '/ˈɡɑːrdnɪŋ/', vietnamese: 'làm vườn', example: 'Gardening is a relaxing activity. (Làm vườn là một hoạt động thư giãn.)' },
      { english: 'collect', type: 'v', pronunciation: '/kəˈlekt/', vietnamese: 'sưu tầm', example: 'He likes to collect old stamps. (Anh ấy thích sưu tầm tem cũ.)' },
      { english: 'instrument', type: 'n', pronunciation: '/ˈɪnstrəmənt/', vietnamese: 'nhạc cụ', example: 'Can you play any musical instrument? (Bạn có thể chơi bất kỳ nhạc cụ nào không?)' },
      { english: 'creative', type: 'adj', pronunciation: '/kriˈeɪtɪv/', vietnamese: 'sáng tạo', example: 'Painting is a creative hobby. (Hội họa là một sở thích sáng tạo.)' },
      { english: 'relaxing', type: 'adj', pronunciation: '/rɪˈlæksɪŋ/', vietnamese: 'thư giãn', example: 'Listening to music is very relaxing. (Nghe nhạc rất thư giãn.)' },
      { english: 'painting', type: 'n', pronunciation: '/ˈpeɪntɪŋ/', vietnamese: 'hội họa', example: 'She took up painting as a hobby. (Cô ấy bắt đầu học vẽ như một sở thích.)' },
      { english: 'dancing', type: 'n', pronunciation: '/ˈdænsɪŋ/', vietnamese: 'khiêu vũ', example: 'Dancing is a great form of exercise. (Khiêu vũ là một hình thức tập thể dục tuyệt vời.)' },
      { english: 'reading', type: 'n', pronunciation: '/ˈriːdɪŋ/', vietnamese: 'đọc sách', example: 'Reading before bed helps me to relax. (Đọc sách trước khi ngủ giúp tôi thư giãn.)' },
      { english: 'hiking', type: 'n', pronunciation: '/ˈhaɪkɪŋ/', vietnamese: 'đi bộ đường dài', example: 'We went hiking in the mountains last weekend. (Chúng tôi đã đi bộ đường dài trên núi vào cuối tuần trước.)' },
      { english: 'camping', type: 'n', pronunciation: '/ˈkæmpɪŋ/', vietnamese: 'cắm trại', example: 'We are going camping this weekend. (Chúng tôi sẽ đi cắm trại vào cuối tuần này.)' },
      { english: 'knitting', type: 'n', pronunciation: '/ˈnɪtɪŋ/', vietnamese: 'đan len', example: 'My grandmother taught me knitting. (Bà tôi đã dạy tôi đan len.)' },
      { english: 'chess', type: 'n', pronunciation: '/tʃes/', vietnamese: 'cờ vua', example: 'Playing chess requires a lot of concentration. (Chơi cờ vua đòi hỏi sự tập trung cao độ.)' },
    ],
  },
  {
    id: 'b1-feelings',
    name: 'Cảm xúc & Tính cách',
    level: 'B1',
    words: [
      { english: 'happy', type: 'adj', pronunciation: '/ˈhæpi/', vietnamese: 'vui vẻ', example: 'She looks very happy today. (Hôm nay trông cô ấy rất vui.)' },
      { english: 'sad', type: 'adj', pronunciation: '/sæd/', vietnamese: 'buồn', example: 'He was sad because he lost his toy. (Cậu bé buồn vì làm mất đồ chơi.)' },
      { english: 'angry', type: 'adj', pronunciation: '/ˈæŋɡri/', vietnamese: 'tức giận', example: 'My father was angry with me. (Bố tôi đã tức giận với tôi.)' },
      { english: 'tired', type: 'adj', pronunciation: '/ˈtaɪərd/', vietnamese: 'mệt mỏi', example: 'After a long day at work, I feel tired. (Sau một ngày dài làm việc, tôi cảm thấy mệt mỏi.)' },
      { english: 'bored', type: 'adj', pronunciation: '/bɔːrd/', vietnamese: 'chán nản', example: 'I feel bored when I have nothing to do. (Tôi cảm thấy chán khi không có gì để làm.)' },
      { english: 'nervous', type: 'adj', pronunciation: '/ˈnɜːrvəs/', vietnamese: 'lo lắng', example: 'I always get nervous before an exam. (Tôi luôn lo lắng trước kỳ thi.)' },
      { english: 'confident', type: 'adj', pronunciation: '/ˈkɑːnfɪdənt/', vietnamese: 'tự tin', example: 'She is a confident speaker. (Cô ấy là một người nói chuyện tự tin.)' },
      { english: 'shy', type: 'adj', pronunciation: '/ʃaɪ/', vietnamese: 'nhút nhát', example: 'He is too shy to talk to new people. (Anh ấy quá nhút nhát để nói chuyện với người mới.)' },
      { english: 'kind', type: 'adj', pronunciation: '/kaɪnd/', vietnamese: 'tốt bụng', example: 'It was very kind of you to help me. (Bạn thật tốt bụng khi giúp tôi.)' },
      { english: 'friendly', type: 'adj', pronunciation: '/ˈfrendli/', vietnamese: 'thân thiện', example: 'The local people are very friendly. (Người dân địa phương rất thân thiện.)' },
    ]
  },

  // ==================== B2 LEVEL ====================
  {
    id: 'b2-technology',
    name: 'Công nghệ',
    level: 'B2',
    words: [
      { english: 'advantage', type: 'n', pronunciation: '/ədˈvæntɪdʒ/', vietnamese: 'lợi thế', example: 'The advantage of this software is its simplicity. (Lợi thế của phần mềm này là sự đơn giản.)' },
      { english: 'disadvantage', type: 'n', pronunciation: '/ˌdɪsədˈvæntɪdʒ/', vietnamese: 'bất lợi', example: 'A major disadvantage is the high cost. (Một bất lợi lớn là chi phí cao.)' },
      { english: 'efficient', type: 'adj', pronunciation: '/ɪˈfɪʃnt/', vietnamese: 'hiệu quả', example: 'This new machine is more efficient. (Cái máy mới này hiệu quả hơn.)' },
      { english: 'reliable', type: 'adj', pronunciation: '/rɪˈlaɪəbl/', vietnamese: 'đáng tin cậy', example: 'We need a reliable internet connection. (Chúng tôi cần kết nối internet đáng tin cậy.)' },
      { english: 'develop', type: 'v', pronunciation: '/dɪˈveləp/', vietnamese: 'phát triển', example: 'They are developing a new type of battery. (Họ đang phát triển một loại pin mới.)' },
      { english: 'innovation', type: 'n', pronunciation: '/ˌɪnəˈveɪʃn/', vietnamese: 'sự đổi mới', example: 'The company is known for its technological innovation. (Công ty được biết đến với sự đổi mới công nghệ.)' },
      { english: 'device', type: 'n', pronunciation: '/dɪˈvaɪs/', vietnamese: 'thiết bị', example: 'A smartphone is a very useful device. (Điện thoại thông minh là một thiết bị rất hữu ích.)' },
      { english: 'artificial intelligence', type: 'n', pronunciation: '/ˌɑːrtɪfɪʃl ɪnˈtelɪdʒəns/', vietnamese: 'trí tuệ nhân tạo', example: 'Artificial intelligence is changing many industries. (Trí tuệ nhân tạo đang thay đổi nhiều ngành công nghiệp.)' },
      { english: 'software', type: 'n', pronunciation: '/ˈsɔːftwer/', vietnamese: 'phần mềm', example: 'You need to install the software first. (Bạn cần cài đặt phần mềm trước.)'},
      { english: 'network', type: 'n', pronunciation: '/ˈnetwɜːrk/', vietnamese: 'mạng lưới', example: 'Our office network is very fast. (Mạng lưới văn phòng của chúng tôi rất nhanh.)'},
      { english: 'algorithm', type: 'n', pronunciation: '/ˈælɡərɪðəm/', vietnamese: 'thuật toán', example: 'The search engine uses a complex algorithm. (Công cụ tìm kiếm sử dụng một thuật toán phức tạp.)'},
      { english: 'gadget', type: 'n', pronunciation: '/ˈɡædʒɪt/', vietnamese: 'dụng cụ, tiện ích', example: 'He loves buying the latest electronic gadgets. (Anh ấy thích mua những tiện ích điện tử mới nhất.)' },
      { english: 'digital', type: 'adj', pronunciation: '/ˈdɪdʒɪtl/', vietnamese: 'kỹ thuật số', example: 'We are living in a digital age. (Chúng ta đang sống trong thời đại kỹ thuật số.)' },
      { english: 'virtual', type: 'adj', pronunciation: '/ˈvɜːrtʃuəl/', vietnamese: 'ảo', example: 'Virtual reality games are becoming more popular. (Trò chơi thực tế ảo đang trở nên phổ biến hơn.)' },
      { english: 'automation', type: 'n', pronunciation: '/ˌɔːtəˈmeɪʃn/', vietnamese: 'sự tự động hóa', example: 'Automation has increased efficiency in factories. (Tự động hóa đã làm tăng hiệu quả trong các nhà máy.)' },
      { english: 'cybersecurity', type: 'n', pronunciation: '/ˈsaɪbərsɪkjʊrəti/', vietnamese: 'an ninh mạng', example: 'Cybersecurity is important to protect personal data. (An ninh mạng rất quan trọng để bảo vệ dữ liệu cá nhân.)' },
      { english: 'interface', type: 'n', pronunciation: '/ˈɪntərfeɪs/', vietnamese: 'giao diện', example: 'The user interface of this app is very friendly. (Giao diện người dùng của ứng dụng này rất thân thiện.)' },
      { english: 'database', type: 'n', pronunciation: '/ˈdeɪtəbeɪs/', vietnamese: 'cơ sở dữ liệu', example: 'All customer information is stored in a database. (Tất cả thông tin khách hàng được lưu trữ trong một cơ sở dữ liệu.)' },
      { english: 'cloud computing', type: 'n', pronunciation: '/klaʊd kəmˈpjuːtɪŋ/', vietnamese: 'điện toán đám mây', example: 'Cloud computing allows us to access data from anywhere. (Điện toán đám mây cho phép chúng ta truy cập dữ liệu từ bất cứ đâu.)' },
      { english: 'bandwidth', type: 'n', pronunciation: '/ˈbændwɪdθ/', vietnamese: 'băng thông', example: 'We need more bandwidth for video conferencing. (Chúng tôi cần thêm băng thông để hội nghị truyền hình.)' },
    ],
  },
  {
    id: 'b2-society',
    name: 'Xã hội',
    level: 'B2',
    words: [
      { english: 'government', type: 'n', pronunciation: '/ˈɡʌvərnmənt/', vietnamese: 'chính phủ', example: 'The government has announced new policies. (Chính phủ đã công bố các chính sách mới.)' },
      { english: 'economy', type: 'n', pronunciation: '/ɪˈkɑːnəmi/', vietnamese: 'nền kinh tế', example: 'The country\'s economy is growing fast. (Nền kinh tế của đất nước đang phát triển nhanh.)' },
      { english: 'community', type: 'n', pronunciation: '/kəˈmjuːnəti/', vietnamese: 'cộng đồng', example: 'He is an active member of the local community. (Anh ấy là một thành viên tích cực của cộng đồng địa phương.)' },
      { english: 'culture', type: 'n', pronunciation: '/ˈkʌltʃər/', vietnamese: 'văn hóa', example: 'I am interested in learning about different cultures. (Tôi thích tìm hiểu về các nền văn hóa khác nhau.)' },
      { english: 'citizen', type: 'n', pronunciation: '/ˈsɪtɪzn/', vietnamese: 'công dân', example: 'He is a citizen of the United States. (Anh ấy là công dân của Hoa Kỳ.)' },
      { english: 'election', type: 'n', pronunciation: '/ɪˈlekʃn/', vietnamese: 'cuộc bầu cử', example: 'The presidential election will be held next year. (Cuộc bầu cử tổng thống sẽ được tổ chức vào năm tới.)' },
      { english: 'generation', type: 'n', pronunciation: '/ˌdʒenəˈreɪʃn/', vietnamese: 'thế hệ', example: 'There is a big difference between the two generations. (Có một sự khác biệt lớn giữa hai thế hệ.)'},
      { english: 'tradition', type: 'n', pronunciation: '/trəˈdɪʃn/', vietnamese: 'truyền thống', example: 'It is a family tradition to eat together on Sundays. (Ăn cơm cùng nhau vào Chủ nhật là truyền thống gia đình.)'},
      { english: 'law', type: 'n', pronunciation: '/lɔː/', vietnamese: 'luật pháp', example: 'Everyone must obey the law. (Mọi người phải tuân thủ pháp luật.)'},
      { english: 'globalization', type: 'n', pronunciation: '/ˌɡloʊbələˈzeɪʃn/', vietnamese: 'toàn cầu hóa', example: 'Globalization has changed the world economy. (Toàn cầu hóa đã làm thay đổi nền kinh tế thế giới.)'},
      { english: 'policy', type: 'n', pronunciation: '/ˈpɑːləsi/', vietnamese: 'chính sách', example: 'The government introduced a new environmental policy. (Chính phủ đã đưa ra một chính sách môi trường mới.)' },
      { english: 'rights', type: 'n', pronunciation: '/raɪts/', vietnamese: 'quyền lợi', example: 'Everyone should be aware of their basic human rights. (Mọi người nên nhận thức được các quyền con người cơ bản của mình.)' },
      { english: 'poverty', type: 'n', pronunciation: '/ˈpɑːvərti/', vietnamese: 'sự nghèo đói', example: 'The organization aims to reduce poverty in developing countries. (Tổ chức này nhằm mục đích giảm nghèo ở các nước đang phát triển.)' },
      { english: 'demographics', type: 'n', pronunciation: '/ˌdeməˈɡræfɪks/', vietnamese: 'nhân khẩu học', example: 'The demographics of the country are changing. (Nhân khẩu học của đất nước đang thay đổi.)' },
      { english: 'urbanization', type: 'n', pronunciation: '/ˌɜːrbənəˈzeɪʃn/', vietnamese: 'đô thị hóa', example: 'Urbanization has led to overcrowding in cities. (Đô thị hóa đã dẫn đến tình trạng quá tải ở các thành phố.)' },
      { english: 'infrastructure', type: 'n', pronunciation: '/ˈɪnfrəstrʌktʃər/', vietnamese: 'cơ sở hạ tầng', example: 'The country needs to invest in its infrastructure. (Đất nước cần đầu tư vào cơ sở hạ tầng của mình.)' },
      { english: 'welfare', type: 'n', pronunciation: '/ˈwelfer/', vietnamese: 'phúc lợi', example: 'The government provides welfare for the unemployed. (Chính phủ cung cấp phúc lợi cho người thất nghiệp.)' },
    ],
  },
  {
    id: 'b2-media',
    name: 'Truyền thông',
    level: 'B2',
    words: [
      { english: 'influence', type: 'n/v', pronunciation: '/ˈɪnfluəns/', vietnamese: 'ảnh hưởng', example: 'The media has a powerful influence on public opinion. (Truyền thông có ảnh hưởng mạnh mẽ đến dư luận.)' },
      { english: 'broadcast', type: 'v', pronunciation: '/ˈbrɔːdkæst/', vietnamese: 'phát sóng', example: 'The concert will be broadcast live. (Buổi hòa nhạc sẽ được phát sóng trực tiếp.)' },
      { english: 'journalist', type: 'n', pronunciation: '/ˈdʒɜːrnəlɪst/', vietnamese: 'nhà báo', example: 'She works as a journalist. (Cô ấy làm nhà báo.)' },
      { english: 'advertisement', type: 'n', pronunciation: '/ˌædvərˈtaɪzmənt/', vietnamese: 'quảng cáo', example: 'I saw an advertisement for a new car on TV. (Tôi đã xem một quảng cáo xe hơi mới trên TV.)' },
      { english: 'source', type: 'n', pronunciation: '/sɔːrs/', vietnamese: 'nguồn (tin)', example: 'It is important to verify the source of the information. (Việc xác minh nguồn thông tin là rất quan trọng.)' },
      { english: 'publish', type: 'v', pronunciation: '/ˈpʌblɪʃ/', vietnamese: 'xuất bản', example: 'The newspaper is published daily. (Tờ báo được xuất bản hàng ngày.)'},
      { english: 'social media', type: 'n', pronunciation: '/ˌsoʊʃl ˈmiːdiə/', vietnamese: 'mạng xã hội', example: 'Many people use social media to stay in touch with friends. (Nhiều người sử dụng mạng xã hội để giữ liên lạc với bạn bè.)'},
    ],
  },
  {
    id: 'b2-finance',
    name: 'Tài chính',
    level: 'B2',
    words: [
      { english: 'investment', type: 'n', pronunciation: '/ɪnˈvestmənt/', vietnamese: 'sự đầu tư', example: 'Real estate can be a good investment. (Bất động sản có thể là một khoản đầu tư tốt.)' },
      { english: 'profit', type: 'n', pronunciation: '/ˈprɑːfɪt/', vietnamese: 'lợi nhuận', example: 'The company made a huge profit last year. (Công ty đã tạo ra lợi nhuận khổng lồ vào năm ngoái.)' },
      { english: 'budget', type: 'n', pronunciation: '/ˈbʌdʒɪt/', vietnamese: 'ngân sách', example: 'We need to create a budget for this project. (Chúng ta cần tạo ngân sách cho dự án này.)' },
      { english: 'loan', type: 'n', pronunciation: '/loʊn/', vietnamese: 'khoản vay', example: 'He took out a loan to buy a car. (Anh ấy đã vay một khoản để mua ô tô.)' },
      { english: 'debt', type: 'n', pronunciation: '/det/', vietnamese: 'nợ', example: 'It is important to pay off your debts. (Việc trả hết nợ của bạn là rất quan trọng.)' },
      { english: 'tax', type: 'n', pronunciation: '/tæks/', vietnamese: 'thuế', example: 'The government collects tax to pay for public services. (Chính phủ thu thuế để chi trả cho các dịch vụ công.)'},
      { english: 'income', type: 'n', pronunciation: '/ˈɪnkʌm/', vietnamese: 'thu nhập', example: 'His monthly income is quite high. (Thu nhập hàng tháng của anh ấy khá cao.)'},
      { english: 'currency', type: 'n', pronunciation: '/ˈkɜːrənsi/', vietnamese: 'tiền tệ', example: 'What is the local currency in Thailand? (Đơn vị tiền tệ địa phương ở Thái Lan là gì?)'},
      { english: 'stock market', type: 'n', pronunciation: '/stɑːk ˈmɑːrkɪt/', vietnamese: 'thị trường chứng khoán', example: 'He lost a lot of money in the stock market. (Anh ấy đã mất rất nhiều tiền trên thị trường chứng khoán.)'},
    ],
  },
  {
    id: 'b2-abstract-nouns',
    name: 'Danh từ trừu tượng',
    level: 'B2',
    words: [
      { english: 'ability', type: 'n', pronunciation: '/əˈbɪləti/', vietnamese: 'khả năng', example: 'She has the ability to solve complex problems. (Cô ấy có khả năng giải quyết các vấn đề phức tạp.)'},
      { english: 'beauty', type: 'n', pronunciation: '/ˈbjuːti/', vietnamese: 'vẻ đẹp', example: 'The beauty of the sunset was breathtaking. (Vẻ đẹp của hoàng hôn thật ngoạn mục.)'},
      { english: 'courage', type: 'n', pronunciation: '/ˈkɜːrɪdʒ/', vietnamese: 'lòng dũng cảm', example: 'It takes courage to admit your mistakes. (Cần có lòng dũng cảm để thừa nhận sai lầm của bạn.)'},
      { english: 'freedom', type: 'n', pronunciation: '/ˈfriːdəm/', vietnamese: 'sự tự do', example: 'Freedom of speech is a basic human right. (Tự do ngôn luận là một quyền cơ bản của con người.)'},
      { english: 'happiness', type: 'n', pronunciation: '/ˈhæpinəs/', vietnamese: 'hạnh phúc', example: 'He found happiness in simple things. (Anh ấy tìm thấy hạnh phúc trong những điều giản đơn.)'},
      { english: 'justice', type: 'n', pronunciation: '/ˈdʒʌstɪs/', vietnamese: 'công lý', example: 'They are fighting for social justice. (Họ đang đấu tranh cho công bằng xã hội.)'},
      { english: 'patience', type: 'n', pronunciation: '/ˈpeɪʃns/', vietnamese: 'sự kiên nhẫn', example: 'You need a lot of patience to be a teacher. (Bạn cần rất nhiều kiên nhẫn để trở thành một giáo viên.)'},
    ],
  },
  {
    id: 'b2-science',
    name: 'Khoa học',
    level: 'B2',
    words: [
      { english: 'science', type: 'n', pronunciation: '/ˈsaɪəns/', vietnamese: 'khoa học', example: 'Science helps us understand the world. (Khoa học giúp chúng ta hiểu thế giới.)' },
      { english: 'research', type: 'n', pronunciation: '/ˈriːsɜːrtʃ/', vietnamese: 'nghiên cứu', example: 'Scientists are doing research on new medicines. (Các nhà khoa học đang nghiên cứu các loại thuốc mới.)' },
      { english: 'experiment', type: 'n', pronunciation: '/ɪkˈsperɪmənt/', vietnamese: 'thí nghiệm', example: 'The students conducted an experiment in the lab. (Các sinh viên đã tiến hành một thí nghiệm trong phòng thí nghiệm.)' },
      { english: 'discovery', type: 'n', pronunciation: '/dɪˈskʌvəri/', vietnamese: 'sự khám phá', example: 'The discovery of penicillin changed medicine. (Việc phát hiện ra penicillin đã thay đổi y học.)' },
      { english: 'theory', type: 'n', pronunciation: '/ˈθiːəri/', vietnamese: 'lý thuyết', example: 'Einstein developed the theory of relativity. (Einstein đã phát triển thuyết tương đối.)' },
      { english: 'evidence', type: 'n', pronunciation: '/ˈevɪdəns/', vietnamese: 'bằng chứng', example: 'There is strong evidence to support his theory. (Có bằng chứng vững chắc để ủng hộ lý thuyết của ông.)' },
      { english: 'analysis', type: 'n', pronunciation: '/əˈnæləsɪs/', vietnamese: 'sự phân tích', example: 'The data analysis revealed some interesting patterns. (Phân tích dữ liệu đã cho thấy một số quy luật thú vị.)' },
    ]
  },

  // ==================== C1 LEVEL ====================
  {
    id: 'c1-academic',
    name: 'Học thuật',
    level: 'C1',
    words: [
      { english: 'analyze', type: 'v', pronunciation: '/ˈænəlaɪz/', vietnamese: 'phân tích', example: 'The scientist will analyze the data. (Nhà khoa học sẽ phân tích dữ liệu.)' },
      { english: 'hypothesis', type: 'n', pronunciation: '/haɪˈpɒθəsɪs/', vietnamese: 'giả thuyết', example: 'The results supported their hypothesis. (Kết quả đã ủng hộ giả thuyết của họ.)' },
      { english: 'ambiguous', type: 'adj', pronunciation: '/æmˈbɪɡjuəs/', vietnamese: 'mơ hồ, không rõ ràng', example: 'The instructions were ambiguous. (Hướng dẫn không rõ ràng.)' },
      { english: 'comprehensive', type: 'adj', pronunciation: '/ˌkɒmprɪˈhensɪv/', vietnamese: 'toàn diện', example: 'The report provides a comprehensive overview. (Báo cáo cung cấp một cái nhìn tổng quan toàn diện.)' },
      { english: 'criterion', type: 'n', pronunciation: '/kraɪˈtɪriən/', vietnamese: 'tiêu chí', example: 'What is the main criterion? (Tiêu chí chính là gì?)' },
      { english: 'plagiarism', type: 'n', pronunciation: '/ˈpleɪdʒərɪzəm/', vietnamese: 'sự đạo văn', example: 'Plagiarism is a serious academic offense. (Đạo văn là một vi phạm học thuật nghiêm trọng.)'},
      { english: 'citation', type: 'n', pronunciation: '/saɪˈteɪʃn/', vietnamese: 'sự trích dẫn', example: 'You must include a citation for every source you use. (Bạn phải bao gồm trích dẫn cho mọi nguồn bạn sử dụng.)'},
      { english: 'implication', type: 'n', pronunciation: '/ˌɪmplɪˈkeɪʃn/', vietnamese: 'hàm ý, ẩn ý', example: 'The new law has serious implications. (Luật mới có những hàm ý nghiêm trọng.)' },
      { english: 'theory', type: 'n', pronunciation: '/ˈθiːəri/', vietnamese: 'lý thuyết', example: 'Einstein\'s theory of relativity changed physics. (Thuyết tương đối của Einstein đã thay đổi ngành vật lý.)' },
      { english: 'methodology', type: 'n', pronunciation: '/ˌmeθəˈdɑːlədʒi/', vietnamese: 'phương pháp luận', example: 'The methodology chapter of the thesis was the most difficult to write. (Chương phương pháp luận của luận án là khó viết nhất.)'},
      { english: 'qualitative', type: 'adj', pronunciation: '/ˈkwɑːlɪteɪtɪv/', vietnamese: 'định tính', example: 'The study used qualitative methods like interviews and observations. (Nghiên cứu đã sử dụng các phương pháp định tính như phỏng vấn và quan sát.)'},
      { english: 'quantitative', type: 'adj', pronunciation: '/ˈkwɑːntəteɪtɪv/', vietnamese: 'định lượng', example: 'Quantitative research involves collecting numerical data. (Nghiên cứu định lượng bao gồm việc thu thập dữ liệu số.)'},
      { english: 'thesis', type: 'n', pronunciation: '/ˈθiːsɪs/', vietnamese: 'luận văn', example: 'She is writing her thesis on modern art. (Cô ấy đang viết luận văn về nghệ thuật hiện đại.)' },
      { english: 'paradigm', type: 'n', pronunciation: '/ˈpærədaɪm/', vietnamese: 'hệ hình, mô hình', example: 'This discovery created a new paradigm in science. (Khám phá này đã tạo ra một hệ hình mới trong khoa học.)' },
      { english: 'empirical', type: 'adj', pronunciation: '/ɪmˈpɪrɪkl/', vietnamese: 'dựa trên kinh nghiệm', example: 'The theory is supported by empirical evidence. (Lý thuyết được hỗ trợ bởi bằng chứng thực nghiệm.)' },
      { english: 'discourse', type: 'n', pronunciation: '/ˈdɪskɔːrs/', vietnamese: 'diễn ngôn, bài luận', example: 'She wrote a discourse on the nature of freedom. (Cô ấy đã viết một bài luận về bản chất của tự do.)' },
      { english: 'synthesis', type: 'n', pronunciation: '/ˈsɪnθəsɪs/', vietnamese: 'sự tổng hợp', example: 'The report is a synthesis of several different studies. (Báo cáo là sự tổng hợp của nhiều nghiên cứu khác nhau.)' },
      { english: 'framework', type: 'n', pronunciation: '/ˈfreɪmwɜːrk/', vietnamese: 'khuôn khổ, sườn', example: 'We need to establish a theoretical framework for our research. (Chúng ta cần thiết lập một khuôn khổ lý thuyết cho nghiên cứu của mình.)' },
      { english: 'longitudinal', type: 'adj', pronunciation: '/ˌlɑːndʒəˈtuːdɪnl/', vietnamese: 'theo chiều dọc, kéo dài', example: 'A longitudinal study follows the same subjects over a long period. (Một nghiên cứu kéo dài theo dõi cùng một đối tượng trong một thời gian dài.)' },
    ],
  },
  {
    id: 'c1-business',
    name: 'Kinh doanh',
    level: 'C1',
    words: [
      { english: 'negotiate', type: 'v', pronunciation: '/nəˈɡoʊʃieɪt/', vietnamese: 'đàm phán', example: 'They are negotiating a new contract. (Họ đang đàm phán một hợp đồng mới.)' },
      { english: 'strategy', type: 'n', pronunciation: '/ˈstrætədʒi/', vietnamese: 'chiến lược', example: 'The company needs a new marketing strategy. (Công ty cần một chiến lược tiếp thị mới.)' },
      { english: 'revenue', type: 'n', pronunciation: '/ˈrevənuː/', vietnamese: 'doanh thu', example: 'The company\'s revenue increased by 10%. (Doanh thu của công ty đã tăng 10%.)' },
      { english: 'competitor', type: 'n', pronunciation: '/kəmˈpetɪtər/', vietnamese: 'đối thủ cạnh tranh', example: 'We need to be better than our competitors. (Chúng ta cần phải tốt hơn các đối thủ cạnh tranh.)' },
      { english: 'entrepreneur', type: 'n', pronunciation: '/ˌɑːntrəprəˈnɜːr/', vietnamese: 'doanh nhân', example: 'He is a successful entrepreneur. (Anh ấy là một doanh nhân thành đạt.)' },
      { english: 'leverage', type: 'v', pronunciation: '/ˈlevərɪdʒ/', vietnamese: 'tận dụng', example: 'We should leverage our brand reputation. (Chúng ta nên tận dụng danh tiếng thương hiệu.)' },
      { english: 'asset', type: 'n', pronunciation: '/ˈæset/', vietnamese: 'tài sản', example: 'Our employees are our most valuable asset. (Nhân viên là tài sản quý giá nhất của chúng tôi.)' },
      { english: 'merger', type: 'n', pronunciation: '/ˈmɜːrdʒər/', vietnamese: 'sự sáp nhập', example: 'The merger of the two companies created a new industry giant. (Sự sáp nhập của hai công ty đã tạo ra một gã khổng lồ mới trong ngành.)'},
      { english: 'equity', type: 'n', pronunciation: '/ˈekwəti/', vietnamese: 'vốn chủ sở hữu', example: 'He sold some of his equity in the company. (Anh ấy đã bán một phần vốn chủ sở hữu của mình trong công ty.)'},
      { english: 'acquisition', type: 'n', pronunciation: '/ˌækwɪˈzɪʃn/', vietnamese: 'sự mua lại', example: 'The company announced a major acquisition of its competitor. (Công ty đã công bố một thương vụ mua lại lớn đối thủ cạnh tranh của mình.)'},
      { english: 'stakeholder', type: 'n', pronunciation: '/ˈsteɪkhoʊldər/', vietnamese: 'bên liên quan', example: 'We need to consider the interests of all stakeholders. (Chúng ta cần xem xét lợi ích của tất cả các bên liên quan.)'},
      { english: 'logistics', type: 'n', pronunciation: '/ləˈdʒɪstɪks/', vietnamese: 'hậu cần', example: 'The logistics of the event were handled by a professional team. (Công tác hậu cần của sự kiện được xử lý bởi một đội ngũ chuyên nghiệp.)' },
      { english: 'outsourcing', type: 'n', pronunciation: '/ˈaʊtsɔːrsɪŋ/', vietnamese: 'thuê ngoài', example: 'Many companies use outsourcing to reduce costs. (Nhiều công ty sử dụng dịch vụ thuê ngoài để giảm chi phí.)' },
      { english: 'franchise', type: 'n', pronunciation: '/ˈfræntʃaɪz/', vietnamese: 'nhượng quyền', example: 'He bought a fast-food franchise. (Anh ấy đã mua một cửa hàng nhượng quyền thức ăn nhanh.)' },
      { english: 'monopoly', type: 'n', pronunciation: '/məˈnɑːpəli/', vietnamese: 'sự độc quyền', example: 'The company has a monopoly on the market. (Công ty này độc quyền trên thị trường.)' },
    ],
  },
  {
    id: 'c1-politics',
    name: 'Chính trị & Luật pháp',
    level: 'C1',
    words: [
      { english: 'legislation', type: 'n', pronunciation: '/ˌledʒɪsˈleɪʃn/', vietnamese: 'pháp luật, luật pháp', example: 'The government has passed new legislation. (Chính phủ đã thông qua luật mới.)' },
      { english: 'advocate', type: 'v', pronunciation: '/ˈædvəkeɪt/', vietnamese: 'biện hộ, ủng hộ', example: 'She is a strong advocate for human rights. (Cô ấy là một người ủng hộ mạnh mẽ cho nhân quyền.)' },
      { english: 'sovereignty', type: 'n', pronunciation: '/ˈsɒvrənti/', vietnamese: 'chủ quyền', example: 'The country fought to defend its sovereignty. (Đất nước đã chiến đấu để bảo vệ chủ quyền.)' },
      { english: 'treaty', type: 'n', pronunciation: '/ˈtriːti/', vietnamese: 'hiệp ước', example: 'The two nations signed a peace treaty. (Hai quốc gia đã ký một hiệp ước hòa bình.)' },
      { english: 'judiciary', type: 'n', pronunciation: '/dʒuˈdɪʃieri/', vietnamese: 'cơ quan tư pháp', example: 'An independent judiciary is essential for a democracy. (Một cơ quan tư pháp độc lập là điều cần thiết cho một nền dân chủ.)' },
      { english: 'diplomacy', type: 'n', pronunciation: '/dɪˈploʊməsi/', vietnamese: 'ngoại giao', example: 'The issue was resolved through diplomacy. (Vấn đề đã được giải quyết thông qua ngoại giao.)'},
      { english: 'bureaucracy', type: 'n', pronunciation: '/bjʊˈrɑːkrəsi/', vietnamese: 'bộ máy quan liêu', example: 'It\'s often difficult to get things done because of the bureaucracy. (Thường rất khó để hoàn thành công việc vì bộ máy quan liêu.)'},
    ],
  },
  {
    id: 'c1-psychology',
    name: 'Tâm lý học',
    level: 'C1',
    words: [
      { english: 'cognitive', type: 'adj', pronunciation: '/ˈkɑːɡnətɪv/', vietnamese: 'thuộc về nhận thức', example: 'Cognitive skills include memory and problem-solving. (Kỹ năng nhận thức bao gồm trí nhớ và giải quyết vấn đề.)' },
      { english: 'bias', type: 'n', pronunciation: '/ˈbaɪəs/', vietnamese: 'thành kiến, thiên vị', example: 'We must be aware of our own cognitive biases. (Chúng ta phải nhận thức được những thành kiến nhận thức của chính mình.)' },
      { english: 'perception', type: 'n', pronunciation: '/pərˈsepʃn/', vietnamese: 'sự nhận thức', example: 'Our perception of reality is influenced by our experiences. (Nhận thức của chúng ta về thực tế bị ảnh hưởng bởi kinh nghiệm.)' },
      { english: 'motivation', type: 'n', pronunciation: '/ˌmoʊtɪˈveɪʃn/', vietnamese: 'động lực', example: 'Understanding student motivation is key to effective teaching. (Hiểu được động lực của học sinh là chìa khóa để giảng dạy hiệu quả.)' },
      { english: 'anxiety', type: 'n', pronunciation: '/æŋˈzaɪəti/', vietnamese: 'sự lo âu', example: 'He suffers from social anxiety. (Anh ấy bị chứng lo âu xã hội.)' },
      { english: 'intrinsic', type: 'adj', pronunciation: '/ɪnˈtrɪnsɪk/', vietnamese: 'bên trong, nội tại', example: 'Intrinsic motivation comes from a personal interest in the task itself. (Động lực nội tại đến từ sự quan tâm cá nhân đối với chính công việc đó.)'},
      { english: 'empathy', type: 'n', pronunciation: '/ˈempəθi/', vietnamese: 'sự đồng cảm', example: 'He felt a sense of empathy for the homeless man. (Anh ấy cảm thấy đồng cảm với người đàn ông vô gia cư.)'},
    ],
  },
  {
    id: 'c1-art-literature',
    name: 'Nghệ thuật & Văn học',
    level: 'C1',
    words: [
      { english: 'novel', type: 'n', pronunciation: '/ˈnɑːvl/', vietnamese: 'tiểu thuyết', example: 'She has written several historical novels. (Cô ấy đã viết nhiều tiểu thuyết lịch sử.)' },
      { english: 'masterpiece', type: 'n', pronunciation: '/ˈmæstərpiːs/', vietnamese: 'kiệt tác', example: 'The Mona Lisa is considered a masterpiece. (Bức Mona Lisa được coi là một kiệt tác.)' },
      { english: 'protagonist', type: 'n', pronunciation: '/proʊˈtæɡənɪst/', vietnamese: 'nhân vật chính', example: 'The protagonist of the story is a young orphan. (Nhân vật chính của câu chuyện là một đứa trẻ mồ côi.)' },
      { english: 'symbolism', type: 'n', pronunciation: '/ˈsɪmbəlɪzəm/', vietnamese: 'chủ nghĩa tượng trưng', example: 'The white dove is a symbol of peace, an example of symbolism. (Bồ câu trắng là biểu tượng của hòa bình, một ví dụ về chủ nghĩa tượng trưng.)' },
      { english: 'metaphor', type: 'n', pronunciation: '/ˈmetəfɔːr/', vietnamese: 'phép ẩn dụ', example: '"The world is a stage" is a famous metaphor. ("Thế giới là một sân khấu" là một phép ẩn dụ nổi tiếng.)' },
      { english: 'aesthetic', type: 'adj', pronunciation: '/esˈθetɪk/', vietnamese: 'thẩm mỹ', example: 'The design has a minimalist aesthetic. (Thiết kế có tính thẩm mỹ tối giản.)' },
      { english: 'critique', type: 'n', pronunciation: '/krɪˈtiːk/', vietnamese: 'bài phê bình', example: 'The art critic wrote a scathing critique of the exhibition. (Nhà phê bình nghệ thuật đã viết một bài phê bình gay gắt về triển lãm.)' },
    ]
  },

  // ==================== C2 LEVEL ====================
  {
    id: 'c2-advanced-concepts',
    name: 'Khái niệm nâng cao',
    level: 'C2',
    words: [
      { english: 'ubiquitous', type: 'adj', pronunciation: '/juːˈbɪkwɪtəs/', vietnamese: 'phổ biến, ở đâu cũng có', example: 'Smartphones have become ubiquitous in modern society. (Điện thoại thông minh đã trở nên phổ biến trong xã hội hiện đại.)' },
      { english: 'ephemeral', type: 'adj', pronunciation: '/ɪˈfemərəl/', vietnamese: 'phù du, chóng tàn', example: 'Fashion trends are often ephemeral. (Các xu hướng thời trang thường chỉ là phù du.)' },
      { english: 'juxtaposition', type: 'n', pronunciation: '/ˌdʒʌkstəpəˈzɪʃn/', vietnamese: 'sự đặt cạnh nhau', example: 'The juxtaposition of wealth and poverty in the city is striking. (Sự đặt cạnh nhau của giàu và nghèo trong thành phố thật đáng kinh ngạc.)' },
      { english: 'eloquent', type: 'adj', pronunciation: '/ˈeləkwənt/', vietnamese: 'hùng hồn, có tài hùng biện', example: 'She delivered an eloquent speech. (Cô ấy đã có một bài phát biểu hùng hồn.)' },
      { english: 'pernicious', type: 'adj', pronunciation: '/pərˈnɪʃəs/', vietnamese: 'độc hại, nguy hiểm', example: 'The pernicious effects of social media are well-documented. (Những ảnh hưởng độc hại của mạng xã hội đã được ghi nhận rõ ràng.)' },
      { english: 'inexorable', type: 'adj', pronunciation: '/ɪnˈeksərəbl/', vietnamese: 'không thể lay chuyển', example: 'The inexorable march of time affects us all. (Bước đi không thể lay chuyển của thời gian ảnh hưởng đến tất cả chúng ta.)' },
      { english: 'cacophony', type: 'n', pronunciation: '/kəˈkɑːfəni/', vietnamese: 'âm thanh hỗn tạp, chói tai', example: 'The city street was filled with a cacophony of car horns. (Đường phố đầy những âm thanh hỗn tạp của còi xe.)' },
      { english: 'veracity', type: 'n', pronunciation: '/vəˈræsəti/', vietnamese: 'tính chân thực', example: 'The police questioned the veracity of his statement. (Cảnh sát đã nghi ngờ tính chân thực của lời khai của anh ta.)' },
      { english: 'anachronism', type: 'n', pronunciation: '/əˈnækrənɪzəm/', vietnamese: 'sự lỗi thời', example: 'In this digital age, writing letters by hand seems like an anachronism. (Trong thời đại kỹ thuật số này, việc viết thư tay có vẻ như là một sự lỗi thời.)'},
      { english: 'quintessential', type: 'adj', pronunciation: '/ˌkwɪntɪˈsenʃl/', vietnamese: 'tinh túy, điển hình', example: 'He is the quintessential British gentleman. (Anh ấy là mẫu quý ông Anh quốc điển hình.)'},
      { english: 'nefarious', type: 'adj', pronunciation: '/nəˈferiəs/', vietnamese: 'bất chính, độc ác', example: 'The villain had a nefarious plan to take over the world. (Kẻ phản diện có một kế hoạch bất chính để chiếm lấy thế giới.)' },
      { english: 'obfuscate', type: 'v', pronunciation: '/ˈɑːbfəskeɪt/', vietnamese: 'làm cho khó hiểu', example: 'The politician tried to obfuscate the issue with irrelevant details. (Chính trị gia đã cố gắng làm cho vấn đề trở nên khó hiểu bằng những chi tiết không liên quan.)'},
      { english: 'sycophant', type: 'n', pronunciation: '/ˈsɪkəfænt/', vietnamese: 'kẻ nịnh hót', example: 'The king was surrounded by sycophants who only told him what he wanted to hear. (Nhà vua bị bao quanh bởi những kẻ nịnh hót chỉ nói với ông những gì ông muốn nghe.)'},
      { english: 'ostentatious', type: 'adj', pronunciation: '/ˌɑːstenˈteɪʃəs/', vietnamese: 'phô trương, khoe khoang', example: 'He lives an ostentatious lifestyle with expensive cars and big parties. (Anh ta sống một lối sống phô trương với xe hơi đắt tiền và những bữa tiệc lớn.)' },
      { english: 'plethora', type: 'n', pronunciation: '/ˈpleθərə/', vietnamese: 'sự thừa thãi', example: 'There is a plethora of information available on the internet. (Có một sự thừa thãi thông tin trên mạng internet.)' },
      { english: 'serendipity', type: 'n', pronunciation: '/ˌserənˈdɪpəti/', vietnamese: 'sự tình cờ may mắn', example: 'Finding that old book in the shop was pure serendipity. (Tìm thấy cuốn sách cũ đó trong cửa hàng hoàn toàn là một sự tình cờ may mắn.)' },
      { english: 'salient', type: 'adj', pronunciation: '/ˈseɪliənt/', vietnamese: 'nổi bật, quan trọng nhất', example: 'The salient point of his argument was that the plan was too expensive. (Điểm nổi bật trong lập luận của anh ấy là kế hoạch quá tốn kém.)' },
      { english: 'prolific', type: 'adj', pronunciation: '/prəˈlɪfɪk/', vietnamese: 'sáng tác nhiều, mắn đẻ', example: 'She was a prolific writer, publishing three novels a year. (Bà là một nhà văn sáng tác nhiều, xuất bản ba tiểu thuyết mỗi năm.)' },
      { english: 'panacea', type: 'n', pronunciation: '/ˌpænəˈsiːə/', vietnamese: 'thuốc chữa bách bệnh', example: 'Unfortunately, there is no panacea for the country\'s economic problems. (Thật không may, không có thuốc chữa bách bệnh cho các vấn đề kinh tế của đất nước.)' },
    ],
  },
  {
    id: 'c2-abstract-ideas',
    name: 'Ý tưởng trừu tượng',
    level: 'C2',
    words: [
      { english: 'paradigm', type: 'n', pronunciation: '/ˈpærədaɪm/', vietnamese: 'hệ hình, mô hình', example: 'The discovery of DNA created a new paradigm in biology. (Việc phát hiện ra DNA đã tạo ra một hệ hình mới trong sinh học.)' },
      { english: 'dichotomy', type: 'n', pronunciation: '/daɪˈkɒtəmi/', vietnamese: 'sự phân đôi', example: 'There is often a dichotomy between what people say and what they do. (Thường có một sự phân đôi giữa những gì người ta nói và những gì họ làm.)' },
      { english: 'zeitgeist', type: 'n', pronunciation: '/ˈzaɪtɡaɪst/', vietnamese: 'tinh thần thời đại', example: 'His music perfectly captured the zeitgeist of the 1960s. (Âm nhạc của ông đã nắm bắt hoàn hảo tinh thần thời đại của những năm 1960.)' },
      { english: 'esoteric', type: 'adj', pronunciation: '/ˌesəˈterɪk/', vietnamese: 'bí truyền, khó hiểu', example: 'He was having an esoteric conversation about philosophy. (Anh ấy đang có một cuộc trò chuyện khó hiểu về triết học.)' },
      { english: 'synergy', type: 'n', pronunciation: '/ˈsɪnərdʒi/', vietnamese: 'sự hợp lực', example: 'The synergy between the two companies resulted in a very successful product. (Sự hợp lực giữa hai công ty đã tạo ra một sản phẩm rất thành công.)' },
      { english: 'heuristic', type: 'n', pronunciation: '/hjuˈrɪstɪk/', vietnamese: 'phương pháp tìm đoán', example: 'Heuristics are mental shortcuts that help us make decisions quickly. (Phương pháp tìm đoán là những lối tắt tinh thần giúp chúng ta đưa ra quyết định nhanh chóng.)'},
      { english: 'empirical', type: 'adj', pronunciation: '/ɪmˈpɪrɪkl/', vietnamese: 'dựa trên kinh nghiệm', example: 'The theory is based on empirical evidence. (Lý thuyết này dựa trên bằng chứng thực nghiệm.)'},
    ],
  },
  {
    id: 'c2-philosophy',
    name: 'Triết học',
    level: 'C2',
    words: [
      { english: 'ontology', type: 'n', pronunciation: '/ɒnˈtɒlədʒi/', vietnamese: 'bản thể luận', example: 'Ontology is the branch of metaphysics dealing with the nature of being. (Bản thể luận là nhánh của siêu hình học nghiên cứu về bản chất của sự tồn tại.)' },
      { english: 'epistemology', type: 'n', pronunciation: '/ɪˌpɪstəˈmɒlədʒi/', vietnamese: 'nhận thức luận', example: 'Epistemology questions what knowledge is and how it can be acquired. (Nhận thức luận đặt câu hỏi kiến thức là gì và làm thế nào để có được nó.)' },
      { english: 'hedonism', type: 'n', pronunciation: '/ˈhiːdənɪzəm/', vietnamese: 'chủ nghĩa khoái lạc', example: 'Hedonism is the ethical theory that pleasure is the highest good. (Chủ nghĩa khoái lạc là học thuyết đạo đức cho rằng khoái lạc là điều tốt đẹp nhất.)' },
      { english: 'stoicism', type: 'n', pronunciation: '/ˈstoʊɪsɪzəm/', vietnamese: 'chủ nghĩa khắc kỷ', example: 'Stoicism teaches the development of self-control. (Chủ nghĩa khắc kỷ dạy về sự phát triển của tự chủ.)' },
      { english: 'existentialism', type: 'n', pronunciation: '/ˌeɡzɪˈstenʃəlɪzəm/', vietnamese: 'chủ nghĩa hiện sinh', example: 'Existentialism emphasizes individual freedom and responsibility. (Chủ nghĩa hiện sinh nhấn mạnh sự tự do và trách nhiệm cá nhân.)' },
      { english: 'utilitarianism', type: 'n', pronunciation: '/juːˌtɪlɪˈteriənɪzəm/', vietnamese: 'chủ nghĩa vị lợi', example: 'Utilitarianism holds that the best action is the one that maximizes utility. (Chủ nghĩa vị lợi cho rằng hành động tốt nhất là hành động tối đa hóa lợi ích.)'},
      { english: 'solipsism', type: 'n', pronunciation: '/ˈsɒlɪpsɪzəm/', vietnamese: 'thuyết duy ngã', example: 'Solipsism is the philosophical idea that only one\'s own mind is sure to exist. (Thuyết duy ngã là ý tưởng triết học cho rằng chỉ có tâm trí của chính mình là chắc chắn tồn tại.)'},
      { english: 'nihilism', type: 'n', pronunciation: '/ˈnaɪɪlɪzəm/', vietnamese: 'thuyết hư vô', example: 'Nihilism is the belief that life is without objective meaning, purpose, or intrinsic value. (Thuyết hư vô là niềm tin rằng cuộc sống không có ý nghĩa, mục đích hay giá trị nội tại khách quan.)'},
      { english: 'determinism', type: 'n', pronunciation: '/dɪˈtɜːrmɪnɪzəm/', vietnamese: 'thuyết quyết định', example: 'Determinism suggests that all events are completely determined by previously existing causes. (Thuyết quyết định cho rằng tất cả các sự kiện đều được quyết định hoàn toàn bởi các nguyên nhân đã tồn tại trước đó.)'},
      { english: 'ethics', type: 'n', pronunciation: '/ˈeθɪks/', vietnamese: 'đạo đức học', example: 'The ethics of artificial intelligence is a complex topic. (Đạo đức học của trí tuệ nhân tạo là một chủ đề phức tạp.)' },
      { english: 'aesthetics', type: 'n', pronunciation: '/esˈθetɪks/', vietnamese: 'mỹ học', example: 'Aesthetics is the branch of philosophy concerned with the nature of beauty. (Mỹ học là nhánh triết học liên quan đến bản chất của cái đẹp.)' },
      { english: 'metaphysics', type: 'n', pronunciation: '/ˌmetəˈfɪzɪks/', vietnamese: 'siêu hình học', example: 'Metaphysics deals with fundamental questions of reality. (Siêu hình học giải quyết những câu hỏi cơ bản về thực tại.)' },
      { english: 'dualism', type: 'n', pronunciation: '/ˈduːəlɪzəm/', vietnamese: 'thuyết nhị nguyên', example: 'Mind-body dualism is the view that the mind and body are distinct and separable. (Thuyết nhị nguyên tâm-vật là quan điểm cho rằng tâm trí và cơ thể là riêng biệt và có thể tách rời.)' },
      { english: 'empiricism', type: 'n', pronunciation: '/ɪmˈpɪrɪsɪzəm/', vietnamese: 'chủ nghĩa kinh nghiệm', example: 'Empiricism asserts that knowledge comes only or primarily from sensory experience. (Chủ nghĩa kinh nghiệm khẳng định rằng kiến thức chỉ đến từ hoặc chủ yếu từ kinh nghiệm cảm quan.)' },
      { english: 'rationalism', type: 'n', pronunciation: '/ˈræʃnəlɪzəm/', vietnamese: 'chủ nghĩa duy lý', example: 'Rationalism is the view that reason is the chief source and test of knowledge. (Chủ nghĩa duy lý là quan điểm cho rằng lý trí là nguồn gốc và phép thử chính của kiến thức.)' },
      { english: 'idealism', type: 'n', pronunciation: '/aɪˈdiːəlɪzəm/', vietnamese: 'chủ nghĩa duy tâm', example: 'Idealism in philosophy asserts that reality is fundamentally mental or otherwise immaterial. (Chủ nghĩa duy tâm trong triết học khẳng định rằng thực tại về cơ bản là tinh thần hoặc phi vật chất.)' },
    ],
  },
];

// Xử lý dữ liệu thô để thêm thuộc tính màu vào mỗi từ
export const WORD_CATEGORIES: Category[] = rawCategories.map(category => ({
  ...category,
  words: category.words.map(word => ({
    ...word,
    example: word.example || 'Example not available. (Chưa có ví dụ.)',
    color: TYPE_COLORS[word.type] || TYPE_COLORS['n/v'],
  })),
}));

export const ALL_WORDS: Word[] = WORD_CATEGORIES.flatMap(category => category.words);